// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIBookingService creates a new instance of MockIBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBookingService {
	mock := &MockIBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIBookingService is an autogenerated mock type for the IBookingService type
type MockIBookingService struct {
	mock.Mock
}

type MockIBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBookingService) EXPECT() *MockIBookingService_Expecter {
	return &MockIBookingService_Expecter{mock: &_m.Mock}
}

// CreateBooking provides a mock function for the type MockIBookingService
func (_mock *MockIBookingService) CreateBooking(ctx context.Context, userID int64, slotOptionID int64) (*param.BookingParam, error) {
	ret := _mock.Called(ctx, userID, slotOptionID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *param.BookingParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*param.BookingParam, error)); ok {
		return returnFunc(ctx, userID, slotOptionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *param.BookingParam); ok {
		r0 = returnFunc(ctx, userID, slotOptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.BookingParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, slotOptionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBookingService_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockIBookingService_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - slotOptionID int64
func (_e *MockIBookingService_Expecter) CreateBooking(ctx interface{}, userID interface{}, slotOptionID interface{}) *MockIBookingService_CreateBooking_Call {
	return &MockIBookingService_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, userID, slotOptionID)}
}

func (_c *MockIBookingService_CreateBooking_Call) Run(run func(ctx context.Context, userID int64, slotOptionID int64)) *MockIBookingService_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBookingService_CreateBooking_Call) Return(bookingParam *param.BookingParam, err error) *MockIBookingService_CreateBooking_Call {
	_c.Call.Return(bookingParam, err)
	return _c
}

func (_c *MockIBookingService_CreateBooking_Call) RunAndReturn(run func(ctx context.Context, userID int64, slotOptionID int64) (*param.BookingParam, error)) *MockIBookingService_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableSlots provides a mock function for the type MockIBookingService
func (_mock *MockIBookingService) GetAvailableSlots(ctx context.Context, businessID int64, serviceOptionID int64, date string, staffID *int64) ([]param.ServiceSlotParam, error) {
	ret := _mock.Called(ctx, businessID, serviceOptionID, date, staffID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlots")
	}

	var r0 []param.ServiceSlotParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, *int64) ([]param.ServiceSlotParam, error)); ok {
		return returnFunc(ctx, businessID, serviceOptionID, date, staffID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, *int64) []param.ServiceSlotParam); ok {
		r0 = returnFunc(ctx, businessID, serviceOptionID, date, staffID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceSlotParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, string, *int64) error); ok {
		r1 = returnFunc(ctx, businessID, serviceOptionID, date, staffID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBookingService_GetAvailableSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableSlots'
type MockIBookingService_GetAvailableSlots_Call struct {
	*mock.Call
}

// GetAvailableSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - serviceOptionID int64
//   - date string
//   - staffID *int64
func (_e *MockIBookingService_Expecter) GetAvailableSlots(ctx interface{}, businessID interface{}, serviceOptionID interface{}, date interface{}, staffID interface{}) *MockIBookingService_GetAvailableSlots_Call {
	return &MockIBookingService_GetAvailableSlots_Call{Call: _e.mock.On("GetAvailableSlots", ctx, businessID, serviceOptionID, date, staffID)}
}

func (_c *MockIBookingService_GetAvailableSlots_Call) Run(run func(ctx context.Context, businessID int64, serviceOptionID int64, date string, staffID *int64)) *MockIBookingService_GetAvailableSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIBookingService_GetAvailableSlots_Call) Return(serviceSlotParams []param.ServiceSlotParam, err error) *MockIBookingService_GetAvailableSlots_Call {
	_c.Call.Return(serviceSlotParams, err)
	return _c
}

func (_c *MockIBookingService_GetAvailableSlots_Call) RunAndReturn(run func(ctx context.Context, businessID int64, serviceOptionID int64, date string, staffID *int64) ([]param.ServiceSlotParam, error)) *MockIBookingService_GetAvailableSlots_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentlyBookedBusinesses provides a mock function for the type MockIBookingService
func (_mock *MockIBookingService) GetRecentlyBookedBusinesses(ctx context.Context, userID int64) ([]param.BusinessProfileParam, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentlyBookedBusinesses")
	}

	var r0 []param.BusinessProfileParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.BusinessProfileParam, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.BusinessProfileParam); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.BusinessProfileParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBookingService_GetRecentlyBookedBusinesses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentlyBookedBusinesses'
type MockIBookingService_GetRecentlyBookedBusinesses_Call struct {
	*mock.Call
}

// GetRecentlyBookedBusinesses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIBookingService_Expecter) GetRecentlyBookedBusinesses(ctx interface{}, userID interface{}) *MockIBookingService_GetRecentlyBookedBusinesses_Call {
	return &MockIBookingService_GetRecentlyBookedBusinesses_Call{Call: _e.mock.On("GetRecentlyBookedBusinesses", ctx, userID)}
}

func (_c *MockIBookingService_GetRecentlyBookedBusinesses_Call) Run(run func(ctx context.Context, userID int64)) *MockIBookingService_GetRecentlyBookedBusinesses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBookingService_GetRecentlyBookedBusinesses_Call) Return(businessProfileParams []param.BusinessProfileParam, err error) *MockIBookingService_GetRecentlyBookedBusinesses_Call {
	_c.Call.Return(businessProfileParams, err)
	return _c
}

func (_c *MockIBookingService_GetRecentlyBookedBusinesses_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]param.BusinessProfileParam, error)) *MockIBookingService_GetRecentlyBookedBusinesses_Call {
	_c.Call.Return(run)
	return _c
}
