// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIBusinessRepo creates a new instance of MockIBusinessRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBusinessRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBusinessRepo {
	mock := &MockIBusinessRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIBusinessRepo is an autogenerated mock type for the IBusinessRepo type
type MockIBusinessRepo struct {
	mock.Mock
}

type MockIBusinessRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBusinessRepo) EXPECT() *MockIBusinessRepo_Expecter {
	return &MockIBusinessRepo_Expecter{mock: &_m.Mock}
}

// InsertBusinessProfile provides a mock function for the type MockIBusinessRepo
func (_mock *MockIBusinessRepo) InsertBusinessProfile(ctx context.Context, tx *sql.Tx, param1 param.BusinessProfileParam) (*param.BusinessProfileParam, error) {
	ret := _mock.Called(ctx, tx, param1)

	if len(ret) == 0 {
		panic("no return value specified for InsertBusinessProfile")
	}

	var r0 *param.BusinessProfileParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.BusinessProfileParam) (*param.BusinessProfileParam, error)); ok {
		return returnFunc(ctx, tx, param1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.BusinessProfileParam) *param.BusinessProfileParam); ok {
		r0 = returnFunc(ctx, tx, param1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.BusinessProfileParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.BusinessProfileParam) error); ok {
		r1 = returnFunc(ctx, tx, param1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBusinessRepo_InsertBusinessProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBusinessProfile'
type MockIBusinessRepo_InsertBusinessProfile_Call struct {
	*mock.Call
}

// InsertBusinessProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - param1 param.BusinessProfileParam
func (_e *MockIBusinessRepo_Expecter) InsertBusinessProfile(ctx interface{}, tx interface{}, param1 interface{}) *MockIBusinessRepo_InsertBusinessProfile_Call {
	return &MockIBusinessRepo_InsertBusinessProfile_Call{Call: _e.mock.On("InsertBusinessProfile", ctx, tx, param1)}
}

func (_c *MockIBusinessRepo_InsertBusinessProfile_Call) Run(run func(ctx context.Context, tx *sql.Tx, param1 param.BusinessProfileParam)) *MockIBusinessRepo_InsertBusinessProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.BusinessProfileParam
		if args[2] != nil {
			arg2 = args[2].(param.BusinessProfileParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBusinessRepo_InsertBusinessProfile_Call) Return(businessProfileParam *param.BusinessProfileParam, err error) *MockIBusinessRepo_InsertBusinessProfile_Call {
	_c.Call.Return(businessProfileParam, err)
	return _c
}

func (_c *MockIBusinessRepo_InsertBusinessProfile_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, param1 param.BusinessProfileParam) (*param.BusinessProfileParam, error)) *MockIBusinessRepo_InsertBusinessProfile_Call {
	_c.Call.Return(run)
	return _c
}

// InsertBusinessWorkingHours provides a mock function for the type MockIBusinessRepo
func (_mock *MockIBusinessRepo) InsertBusinessWorkingHours(ctx context.Context, tx *sql.Tx, param1 param.BusinessProfileParam) error {
	ret := _mock.Called(ctx, tx, param1)

	if len(ret) == 0 {
		panic("no return value specified for InsertBusinessWorkingHours")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.BusinessProfileParam) error); ok {
		r0 = returnFunc(ctx, tx, param1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBusinessRepo_InsertBusinessWorkingHours_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBusinessWorkingHours'
type MockIBusinessRepo_InsertBusinessWorkingHours_Call struct {
	*mock.Call
}

// InsertBusinessWorkingHours is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - param1 param.BusinessProfileParam
func (_e *MockIBusinessRepo_Expecter) InsertBusinessWorkingHours(ctx interface{}, tx interface{}, param1 interface{}) *MockIBusinessRepo_InsertBusinessWorkingHours_Call {
	return &MockIBusinessRepo_InsertBusinessWorkingHours_Call{Call: _e.mock.On("InsertBusinessWorkingHours", ctx, tx, param1)}
}

func (_c *MockIBusinessRepo_InsertBusinessWorkingHours_Call) Run(run func(ctx context.Context, tx *sql.Tx, param1 param.BusinessProfileParam)) *MockIBusinessRepo_InsertBusinessWorkingHours_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.BusinessProfileParam
		if args[2] != nil {
			arg2 = args[2].(param.BusinessProfileParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBusinessRepo_InsertBusinessWorkingHours_Call) Return(err error) *MockIBusinessRepo_InsertBusinessWorkingHours_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBusinessRepo_InsertBusinessWorkingHours_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, param1 param.BusinessProfileParam) error) *MockIBusinessRepo_InsertBusinessWorkingHours_Call {
	_c.Call.Return(run)
	return _c
}
