// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIServiceRepo creates a new instance of MockIServiceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServiceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServiceRepo {
	mock := &MockIServiceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIServiceRepo is an autogenerated mock type for the IServiceRepo type
type MockIServiceRepo struct {
	mock.Mock
}

type MockIServiceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServiceRepo) EXPECT() *MockIServiceRepo_Expecter {
	return &MockIServiceRepo_Expecter{mock: &_m.Mock}
}

// DeleteServiceOptionsByServiceID provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) DeleteServiceOptionsByServiceID(ctx context.Context, tx *sql.Tx, serviceID int64) error {
	ret := _mock.Called(ctx, tx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceOptionsByServiceID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64) error); ok {
		r0 = returnFunc(ctx, tx, serviceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceRepo_DeleteServiceOptionsByServiceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServiceOptionsByServiceID'
type MockIServiceRepo_DeleteServiceOptionsByServiceID_Call struct {
	*mock.Call
}

// DeleteServiceOptionsByServiceID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - serviceID int64
func (_e *MockIServiceRepo_Expecter) DeleteServiceOptionsByServiceID(ctx interface{}, tx interface{}, serviceID interface{}) *MockIServiceRepo_DeleteServiceOptionsByServiceID_Call {
	return &MockIServiceRepo_DeleteServiceOptionsByServiceID_Call{Call: _e.mock.On("DeleteServiceOptionsByServiceID", ctx, tx, serviceID)}
}

func (_c *MockIServiceRepo_DeleteServiceOptionsByServiceID_Call) Run(run func(ctx context.Context, tx *sql.Tx, serviceID int64)) *MockIServiceRepo_DeleteServiceOptionsByServiceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_DeleteServiceOptionsByServiceID_Call) Return(err error) *MockIServiceRepo_DeleteServiceOptionsByServiceID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceRepo_DeleteServiceOptionsByServiceID_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, serviceID int64) error) *MockIServiceRepo_DeleteServiceOptionsByServiceID_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceOptionItemsByOptionID provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) GetServiceOptionItemsByOptionID(ctx context.Context, serviceOptionID int64) ([]param.ServiceOptionItemParam, error) {
	ret := _mock.Called(ctx, serviceOptionID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceOptionItemsByOptionID")
	}

	var r0 []param.ServiceOptionItemParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.ServiceOptionItemParam, error)); ok {
		return returnFunc(ctx, serviceOptionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.ServiceOptionItemParam); ok {
		r0 = returnFunc(ctx, serviceOptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceOptionItemParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, serviceOptionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_GetServiceOptionItemsByOptionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceOptionItemsByOptionID'
type MockIServiceRepo_GetServiceOptionItemsByOptionID_Call struct {
	*mock.Call
}

// GetServiceOptionItemsByOptionID is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceOptionID int64
func (_e *MockIServiceRepo_Expecter) GetServiceOptionItemsByOptionID(ctx interface{}, serviceOptionID interface{}) *MockIServiceRepo_GetServiceOptionItemsByOptionID_Call {
	return &MockIServiceRepo_GetServiceOptionItemsByOptionID_Call{Call: _e.mock.On("GetServiceOptionItemsByOptionID", ctx, serviceOptionID)}
}

func (_c *MockIServiceRepo_GetServiceOptionItemsByOptionID_Call) Run(run func(ctx context.Context, serviceOptionID int64)) *MockIServiceRepo_GetServiceOptionItemsByOptionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_GetServiceOptionItemsByOptionID_Call) Return(serviceOptionItemParams []param.ServiceOptionItemParam, err error) *MockIServiceRepo_GetServiceOptionItemsByOptionID_Call {
	_c.Call.Return(serviceOptionItemParams, err)
	return _c
}

func (_c *MockIServiceRepo_GetServiceOptionItemsByOptionID_Call) RunAndReturn(run func(ctx context.Context, serviceOptionID int64) ([]param.ServiceOptionItemParam, error)) *MockIServiceRepo_GetServiceOptionItemsByOptionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceOptionItemsByOptionIDIncludeDeleted provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) GetServiceOptionItemsByOptionIDIncludeDeleted(ctx context.Context, serviceOptionID int64) ([]param.ServiceOptionItemParam, error) {
	ret := _mock.Called(ctx, serviceOptionID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceOptionItemsByOptionIDIncludeDeleted")
	}

	var r0 []param.ServiceOptionItemParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.ServiceOptionItemParam, error)); ok {
		return returnFunc(ctx, serviceOptionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.ServiceOptionItemParam); ok {
		r0 = returnFunc(ctx, serviceOptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceOptionItemParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, serviceOptionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceOptionItemsByOptionIDIncludeDeleted'
type MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call struct {
	*mock.Call
}

// GetServiceOptionItemsByOptionIDIncludeDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceOptionID int64
func (_e *MockIServiceRepo_Expecter) GetServiceOptionItemsByOptionIDIncludeDeleted(ctx interface{}, serviceOptionID interface{}) *MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call {
	return &MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call{Call: _e.mock.On("GetServiceOptionItemsByOptionIDIncludeDeleted", ctx, serviceOptionID)}
}

func (_c *MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call) Run(run func(ctx context.Context, serviceOptionID int64)) *MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call) Return(serviceOptionItemParams []param.ServiceOptionItemParam, err error) *MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call {
	_c.Call.Return(serviceOptionItemParams, err)
	return _c
}

func (_c *MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call) RunAndReturn(run func(ctx context.Context, serviceOptionID int64) ([]param.ServiceOptionItemParam, error)) *MockIServiceRepo_GetServiceOptionItemsByOptionIDIncludeDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceOptionsByServiceID provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) GetServiceOptionsByServiceID(ctx context.Context, serviceID int64) ([]param.ServiceOptionParam, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceOptionsByServiceID")
	}

	var r0 []param.ServiceOptionParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.ServiceOptionParam, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.ServiceOptionParam); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceOptionParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_GetServiceOptionsByServiceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceOptionsByServiceID'
type MockIServiceRepo_GetServiceOptionsByServiceID_Call struct {
	*mock.Call
}

// GetServiceOptionsByServiceID is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID int64
func (_e *MockIServiceRepo_Expecter) GetServiceOptionsByServiceID(ctx interface{}, serviceID interface{}) *MockIServiceRepo_GetServiceOptionsByServiceID_Call {
	return &MockIServiceRepo_GetServiceOptionsByServiceID_Call{Call: _e.mock.On("GetServiceOptionsByServiceID", ctx, serviceID)}
}

func (_c *MockIServiceRepo_GetServiceOptionsByServiceID_Call) Run(run func(ctx context.Context, serviceID int64)) *MockIServiceRepo_GetServiceOptionsByServiceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_GetServiceOptionsByServiceID_Call) Return(serviceOptionParams []param.ServiceOptionParam, err error) *MockIServiceRepo_GetServiceOptionsByServiceID_Call {
	_c.Call.Return(serviceOptionParams, err)
	return _c
}

func (_c *MockIServiceRepo_GetServiceOptionsByServiceID_Call) RunAndReturn(run func(ctx context.Context, serviceID int64) ([]param.ServiceOptionParam, error)) *MockIServiceRepo_GetServiceOptionsByServiceID_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicesByBusinessID provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) GetServicesByBusinessID(ctx context.Context, businessID int64) ([]param.ServiceParam, error) {
	ret := _mock.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetServicesByBusinessID")
	}

	var r0 []param.ServiceParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.ServiceParam, error)); ok {
		return returnFunc(ctx, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.ServiceParam); ok {
		r0 = returnFunc(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_GetServicesByBusinessID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicesByBusinessID'
type MockIServiceRepo_GetServicesByBusinessID_Call struct {
	*mock.Call
}

// GetServicesByBusinessID is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
func (_e *MockIServiceRepo_Expecter) GetServicesByBusinessID(ctx interface{}, businessID interface{}) *MockIServiceRepo_GetServicesByBusinessID_Call {
	return &MockIServiceRepo_GetServicesByBusinessID_Call{Call: _e.mock.On("GetServicesByBusinessID", ctx, businessID)}
}

func (_c *MockIServiceRepo_GetServicesByBusinessID_Call) Run(run func(ctx context.Context, businessID int64)) *MockIServiceRepo_GetServicesByBusinessID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_GetServicesByBusinessID_Call) Return(serviceParams []param.ServiceParam, err error) *MockIServiceRepo_GetServicesByBusinessID_Call {
	_c.Call.Return(serviceParams, err)
	return _c
}

func (_c *MockIServiceRepo_GetServicesByBusinessID_Call) RunAndReturn(run func(ctx context.Context, businessID int64) ([]param.ServiceParam, error)) *MockIServiceRepo_GetServicesByBusinessID_Call {
	_c.Call.Return(run)
	return _c
}

// HasBookingForService provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) HasBookingForService(ctx context.Context, serviceID int64) (bool, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for HasBookingForService")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_HasBookingForService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBookingForService'
type MockIServiceRepo_HasBookingForService_Call struct {
	*mock.Call
}

// HasBookingForService is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID int64
func (_e *MockIServiceRepo_Expecter) HasBookingForService(ctx interface{}, serviceID interface{}) *MockIServiceRepo_HasBookingForService_Call {
	return &MockIServiceRepo_HasBookingForService_Call{Call: _e.mock.On("HasBookingForService", ctx, serviceID)}
}

func (_c *MockIServiceRepo_HasBookingForService_Call) Run(run func(ctx context.Context, serviceID int64)) *MockIServiceRepo_HasBookingForService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_HasBookingForService_Call) Return(b bool, err error) *MockIServiceRepo_HasBookingForService_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIServiceRepo_HasBookingForService_Call) RunAndReturn(run func(ctx context.Context, serviceID int64) (bool, error)) *MockIServiceRepo_HasBookingForService_Call {
	_c.Call.Return(run)
	return _c
}

// InsertServiceOptionItem provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) InsertServiceOptionItem(ctx context.Context, tx *sql.Tx, p param.ServiceOptionItemParam) error {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertServiceOptionItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceOptionItemParam) error); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceRepo_InsertServiceOptionItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertServiceOptionItem'
type MockIServiceRepo_InsertServiceOptionItem_Call struct {
	*mock.Call
}

// InsertServiceOptionItem is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServiceOptionItemParam
func (_e *MockIServiceRepo_Expecter) InsertServiceOptionItem(ctx interface{}, tx interface{}, p interface{}) *MockIServiceRepo_InsertServiceOptionItem_Call {
	return &MockIServiceRepo_InsertServiceOptionItem_Call{Call: _e.mock.On("InsertServiceOptionItem", ctx, tx, p)}
}

func (_c *MockIServiceRepo_InsertServiceOptionItem_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServiceOptionItemParam)) *MockIServiceRepo_InsertServiceOptionItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServiceOptionItemParam
		if args[2] != nil {
			arg2 = args[2].(param.ServiceOptionItemParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_InsertServiceOptionItem_Call) Return(err error) *MockIServiceRepo_InsertServiceOptionItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceRepo_InsertServiceOptionItem_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServiceOptionItemParam) error) *MockIServiceRepo_InsertServiceOptionItem_Call {
	_c.Call.Return(run)
	return _c
}

// InsertService provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) InsertService(ctx context.Context, tx *sql.Tx, p param.ServiceParam) (*param.ServiceParam, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertService")
	}

	var r0 *param.ServiceParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceParam) (*param.ServiceParam, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceParam) *param.ServiceParam); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.ServiceParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.ServiceParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_InsertService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertService'
type MockIServiceRepo_InsertService_Call struct {
	*mock.Call
}

// InsertService is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServiceParam
func (_e *MockIServiceRepo_Expecter) InsertService(ctx interface{}, tx interface{}, p interface{}) *MockIServiceRepo_InsertService_Call {
	return &MockIServiceRepo_InsertService_Call{Call: _e.mock.On("InsertService", ctx, tx, p)}
}

func (_c *MockIServiceRepo_InsertService_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServiceParam)) *MockIServiceRepo_InsertService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServiceParam
		if args[2] != nil {
			arg2 = args[2].(param.ServiceParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_InsertService_Call) Return(serviceParam *param.ServiceParam, err error) *MockIServiceRepo_InsertService_Call {
	_c.Call.Return(serviceParam, err)
	return _c
}

func (_c *MockIServiceRepo_InsertService_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServiceParam) (*param.ServiceParam, error)) *MockIServiceRepo_InsertService_Call {
	_c.Call.Return(run)
	return _c
}

// InsertServiceOption provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) InsertServiceOption(ctx context.Context, tx *sql.Tx, p param.ServiceOptionParam) (*param.ServiceOptionParam, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertServiceOption")
	}

	var r0 *param.ServiceOptionParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceOptionParam) (*param.ServiceOptionParam, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceOptionParam) *param.ServiceOptionParam); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.ServiceOptionParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.ServiceOptionParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_InsertServiceOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertServiceOption'
type MockIServiceRepo_InsertServiceOption_Call struct {
	*mock.Call
}

// InsertServiceOption is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServiceOptionParam
func (_e *MockIServiceRepo_Expecter) InsertServiceOption(ctx interface{}, tx interface{}, p interface{}) *MockIServiceRepo_InsertServiceOption_Call {
	return &MockIServiceRepo_InsertServiceOption_Call{Call: _e.mock.On("InsertServiceOption", ctx, tx, p)}
}

func (_c *MockIServiceRepo_InsertServiceOption_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServiceOptionParam)) *MockIServiceRepo_InsertServiceOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServiceOptionParam
		if args[2] != nil {
			arg2 = args[2].(param.ServiceOptionParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_InsertServiceOption_Call) Return(serviceOptionParam *param.ServiceOptionParam, err error) *MockIServiceRepo_InsertServiceOption_Call {
	_c.Call.Return(serviceOptionParam, err)
	return _c
}

func (_c *MockIServiceRepo_InsertServiceOption_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServiceOptionParam) (*param.ServiceOptionParam, error)) *MockIServiceRepo_InsertServiceOption_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteService provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) SoftDeleteService(ctx context.Context, tx *sql.Tx, serviceID int64, businessID int64) error {
	ret := _mock.Called(ctx, tx, serviceID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64) error); ok {
		r0 = returnFunc(ctx, tx, serviceID, businessID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceRepo_SoftDeleteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteService'
type MockIServiceRepo_SoftDeleteService_Call struct {
	*mock.Call
}

// SoftDeleteService is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - serviceID int64
//   - businessID int64
func (_e *MockIServiceRepo_Expecter) SoftDeleteService(ctx interface{}, tx interface{}, serviceID interface{}, businessID interface{}) *MockIServiceRepo_SoftDeleteService_Call {
	return &MockIServiceRepo_SoftDeleteService_Call{Call: _e.mock.On("SoftDeleteService", ctx, tx, serviceID, businessID)}
}

func (_c *MockIServiceRepo_SoftDeleteService_Call) Run(run func(ctx context.Context, tx *sql.Tx, serviceID int64, businessID int64)) *MockIServiceRepo_SoftDeleteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_SoftDeleteService_Call) Return(err error) *MockIServiceRepo_SoftDeleteService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceRepo_SoftDeleteService_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, serviceID int64, businessID int64) error) *MockIServiceRepo_SoftDeleteService_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateService provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) UpdateService(ctx context.Context, tx *sql.Tx, p param.ServiceParam) (*param.ServiceParam, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateService")
	}

	var r0 *param.ServiceParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceParam) (*param.ServiceParam, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceParam) *param.ServiceParam); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.ServiceParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.ServiceParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_UpdateService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateService'
type MockIServiceRepo_UpdateService_Call struct {
	*mock.Call
}

// UpdateService is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServiceParam
func (_e *MockIServiceRepo_Expecter) UpdateService(ctx interface{}, tx interface{}, p interface{}) *MockIServiceRepo_UpdateService_Call {
	return &MockIServiceRepo_UpdateService_Call{Call: _e.mock.On("UpdateService", ctx, tx, p)}
}

func (_c *MockIServiceRepo_UpdateService_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServiceParam)) *MockIServiceRepo_UpdateService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServiceParam
		if args[2] != nil {
			arg2 = args[2].(param.ServiceParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_UpdateService_Call) Return(serviceParam *param.ServiceParam, err error) *MockIServiceRepo_UpdateService_Call {
	_c.Call.Return(serviceParam, err)
	return _c
}

func (_c *MockIServiceRepo_UpdateService_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServiceParam) (*param.ServiceParam, error)) *MockIServiceRepo_UpdateService_Call {
	_c.Call.Return(run)
	return _c
}
