// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIBookingRepo creates a new instance of MockIBookingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBookingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBookingRepo {
	mock := &MockIBookingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIBookingRepo is an autogenerated mock type for the IBookingRepo type
type MockIBookingRepo struct {
	mock.Mock
}

type MockIBookingRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBookingRepo) EXPECT() *MockIBookingRepo_Expecter {
	return &MockIBookingRepo_Expecter{mock: &_m.Mock}
}

// GetAvailableSlots provides a mock function for the type MockIBookingRepo
func (_mock *MockIBookingRepo) GetAvailableSlots(ctx context.Context, businessID int64, serviceOptionID int64, date string, staffID *int64) ([]param.ServiceSlotParam, error) {
	ret := _mock.Called(ctx, businessID, serviceOptionID, date, staffID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlots")
	}

	var r0 []param.ServiceSlotParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, *int64) ([]param.ServiceSlotParam, error)); ok {
		return returnFunc(ctx, businessID, serviceOptionID, date, staffID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, *int64) []param.ServiceSlotParam); ok {
		r0 = returnFunc(ctx, businessID, serviceOptionID, date, staffID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceSlotParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, string, *int64) error); ok {
		r1 = returnFunc(ctx, businessID, serviceOptionID, date, staffID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBookingRepo_GetAvailableSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableSlots'
type MockIBookingRepo_GetAvailableSlots_Call struct {
	*mock.Call
}

// GetAvailableSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - serviceOptionID int64
//   - date string
//   - staffID *int64
func (_e *MockIBookingRepo_Expecter) GetAvailableSlots(ctx interface{}, businessID interface{}, serviceOptionID interface{}, date interface{}, staffID interface{}) *MockIBookingRepo_GetAvailableSlots_Call {
	return &MockIBookingRepo_GetAvailableSlots_Call{Call: _e.mock.On("GetAvailableSlots", ctx, businessID, serviceOptionID, date, staffID)}
}

func (_c *MockIBookingRepo_GetAvailableSlots_Call) Run(run func(ctx context.Context, businessID int64, serviceOptionID int64, date string, staffID *int64)) *MockIBookingRepo_GetAvailableSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIBookingRepo_GetAvailableSlots_Call) Return(serviceSlotParams []param.ServiceSlotParam, err error) *MockIBookingRepo_GetAvailableSlots_Call {
	_c.Call.Return(serviceSlotParams, err)
	return _c
}

func (_c *MockIBookingRepo_GetAvailableSlots_Call) RunAndReturn(run func(ctx context.Context, businessID int64, serviceOptionID int64, date string, staffID *int64) ([]param.ServiceSlotParam, error)) *MockIBookingRepo_GetAvailableSlots_Call {
	_c.Call.Return(run)
	return _c
}

// InsertBooking provides a mock function for the type MockIBookingRepo
func (_mock *MockIBookingRepo) InsertBooking(ctx context.Context, userID int64, slotOptionID int64) (*param.BookingParam, error) {
	ret := _mock.Called(ctx, userID, slotOptionID)

	if len(ret) == 0 {
		panic("no return value specified for InsertBooking")
	}

	var r0 *param.BookingParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*param.BookingParam, error)); ok {
		return returnFunc(ctx, userID, slotOptionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *param.BookingParam); ok {
		r0 = returnFunc(ctx, userID, slotOptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.BookingParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, slotOptionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBookingRepo_InsertBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBooking'
type MockIBookingRepo_InsertBooking_Call struct {
	*mock.Call
}

// InsertBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - slotOptionID int64
func (_e *MockIBookingRepo_Expecter) InsertBooking(ctx interface{}, userID interface{}, slotOptionID interface{}) *MockIBookingRepo_InsertBooking_Call {
	return &MockIBookingRepo_InsertBooking_Call{Call: _e.mock.On("InsertBooking", ctx, userID, slotOptionID)}
}

func (_c *MockIBookingRepo_InsertBooking_Call) Run(run func(ctx context.Context, userID int64, slotOptionID int64)) *MockIBookingRepo_InsertBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBookingRepo_InsertBooking_Call) Return(bookingParam *param.BookingParam, err error) *MockIBookingRepo_InsertBooking_Call {
	_c.Call.Return(bookingParam, err)
	return _c
}

func (_c *MockIBookingRepo_InsertBooking_Call) RunAndReturn(run func(ctx context.Context, userID int64, slotOptionID int64) (*param.BookingParam, error)) *MockIBookingRepo_InsertBooking_Call {
	_c.Call.Return(run)
	return _c
}
