// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIProfileRepo creates a new instance of MockIProfileRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIProfileRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIProfileRepo {
	mock := &MockIProfileRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIProfileRepo is an autogenerated mock type for the IProfileRepo type
type MockIProfileRepo struct {
	mock.Mock
}

type MockIProfileRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIProfileRepo) EXPECT() *MockIProfileRepo_Expecter {
	return &MockIProfileRepo_Expecter{mock: &_m.Mock}
}
