// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockILeaveRepo creates a new instance of MockILeaveRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILeaveRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILeaveRepo {
	mock := &MockILeaveRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILeaveRepo is an autogenerated mock type for the ILeaveRepo type
type MockILeaveRepo struct {
	mock.Mock
}

type MockILeaveRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILeaveRepo) EXPECT() *MockILeaveRepo_Expecter {
	return &MockILeaveRepo_Expecter{mock: &_m.Mock}
}

// GetLeaveApplicationByID provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) GetLeaveApplicationByID(ctx context.Context, leaveID int64) (*param.LeaveApplicationParam, error) {
	ret := _mock.Called(ctx, leaveID)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaveApplicationByID")
	}

	var r0 *param.LeaveApplicationParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*param.LeaveApplicationParam, error)); ok {
		return returnFunc(ctx, leaveID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *param.LeaveApplicationParam); ok {
		r0 = returnFunc(ctx, leaveID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.LeaveApplicationParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, leaveID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILeaveRepo_GetLeaveApplicationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaveApplicationByID'
type MockILeaveRepo_GetLeaveApplicationByID_Call struct {
	*mock.Call
}

// GetLeaveApplicationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - leaveID int64
func (_e *MockILeaveRepo_Expecter) GetLeaveApplicationByID(ctx interface{}, leaveID interface{}) *MockILeaveRepo_GetLeaveApplicationByID_Call {
	return &MockILeaveRepo_GetLeaveApplicationByID_Call{Call: _e.mock.On("GetLeaveApplicationByID", ctx, leaveID)}
}

func (_c *MockILeaveRepo_GetLeaveApplicationByID_Call) Run(run func(ctx context.Context, leaveID int64)) *MockILeaveRepo_GetLeaveApplicationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_GetLeaveApplicationByID_Call) Return(leaveApplicationParam *param.LeaveApplicationParam, err error) *MockILeaveRepo_GetLeaveApplicationByID_Call {
	_c.Call.Return(leaveApplicationParam, err)
	return _c
}

func (_c *MockILeaveRepo_GetLeaveApplicationByID_Call) RunAndReturn(run func(ctx context.Context, leaveID int64) (*param.LeaveApplicationParam, error)) *MockILeaveRepo_GetLeaveApplicationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaveApplicationsByBusinessID provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) GetLeaveApplicationsByBusinessID(ctx context.Context, businessID int64) ([]param.LeaveApplicationParam, error) {
	ret := _mock.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaveApplicationsByBusinessID")
	}

	var r0 []param.LeaveApplicationParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.LeaveApplicationParam, error)); ok {
		return returnFunc(ctx, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.LeaveApplicationParam); ok {
		r0 = returnFunc(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.LeaveApplicationParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaveApplicationsByBusinessID'
type MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call struct {
	*mock.Call
}

// GetLeaveApplicationsByBusinessID is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
func (_e *MockILeaveRepo_Expecter) GetLeaveApplicationsByBusinessID(ctx interface{}, businessID interface{}) *MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call {
	return &MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call{Call: _e.mock.On("GetLeaveApplicationsByBusinessID", ctx, businessID)}
}

func (_c *MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call) Run(run func(ctx context.Context, businessID int64)) *MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call) Return(leaveApplicationParams []param.LeaveApplicationParam, err error) *MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call {
	_c.Call.Return(leaveApplicationParams, err)
	return _c
}

func (_c *MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call) RunAndReturn(run func(ctx context.Context, businessID int64) ([]param.LeaveApplicationParam, error)) *MockILeaveRepo_GetLeaveApplicationsByBusinessID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaveApplicationsByStaffID provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) GetLeaveApplicationsByStaffID(ctx context.Context, staffID int64) ([]param.LeaveApplicationParam, error) {
	ret := _mock.Called(ctx, staffID)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaveApplicationsByStaffID")
	}

	var r0 []param.LeaveApplicationParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.LeaveApplicationParam, error)); ok {
		return returnFunc(ctx, staffID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.LeaveApplicationParam); ok {
		r0 = returnFunc(ctx, staffID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.LeaveApplicationParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, staffID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILeaveRepo_GetLeaveApplicationsByStaffID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaveApplicationsByStaffID'
type MockILeaveRepo_GetLeaveApplicationsByStaffID_Call struct {
	*mock.Call
}

// GetLeaveApplicationsByStaffID is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int64
func (_e *MockILeaveRepo_Expecter) GetLeaveApplicationsByStaffID(ctx interface{}, staffID interface{}) *MockILeaveRepo_GetLeaveApplicationsByStaffID_Call {
	return &MockILeaveRepo_GetLeaveApplicationsByStaffID_Call{Call: _e.mock.On("GetLeaveApplicationsByStaffID", ctx, staffID)}
}

func (_c *MockILeaveRepo_GetLeaveApplicationsByStaffID_Call) Run(run func(ctx context.Context, staffID int64)) *MockILeaveRepo_GetLeaveApplicationsByStaffID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_GetLeaveApplicationsByStaffID_Call) Return(leaveApplicationParams []param.LeaveApplicationParam, err error) *MockILeaveRepo_GetLeaveApplicationsByStaffID_Call {
	_c.Call.Return(leaveApplicationParams, err)
	return _c
}

func (_c *MockILeaveRepo_GetLeaveApplicationsByStaffID_Call) RunAndReturn(run func(ctx context.Context, staffID int64) ([]param.LeaveApplicationParam, error)) *MockILeaveRepo_GetLeaveApplicationsByStaffID_Call {
	_c.Call.Return(run)
	return _c
}

// HasOverlappingLeave provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) HasOverlappingLeave(ctx context.Context, staffID int64, startDate string, endDate string) (bool, error) {
	ret := _mock.Called(ctx, staffID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for HasOverlappingLeave")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) (bool, error)); ok {
		return returnFunc(ctx, staffID, startDate, endDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) bool); ok {
		r0 = returnFunc(ctx, staffID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, staffID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILeaveRepo_HasOverlappingLeave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasOverlappingLeave'
type MockILeaveRepo_HasOverlappingLeave_Call struct {
	*mock.Call
}

// HasOverlappingLeave is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int64
//   - startDate string
//   - endDate string
func (_e *MockILeaveRepo_Expecter) HasOverlappingLeave(ctx interface{}, staffID interface{}, startDate interface{}, endDate interface{}) *MockILeaveRepo_HasOverlappingLeave_Call {
	return &MockILeaveRepo_HasOverlappingLeave_Call{Call: _e.mock.On("HasOverlappingLeave", ctx, staffID, startDate, endDate)}
}

func (_c *MockILeaveRepo_HasOverlappingLeave_Call) Run(run func(ctx context.Context, staffID int64, startDate string, endDate string)) *MockILeaveRepo_HasOverlappingLeave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_HasOverlappingLeave_Call) Return(b bool, err error) *MockILeaveRepo_HasOverlappingLeave_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockILeaveRepo_HasOverlappingLeave_Call) RunAndReturn(run func(ctx context.Context, staffID int64, startDate string, endDate string) (bool, error)) *MockILeaveRepo_HasOverlappingLeave_Call {
	_c.Call.Return(run)
	return _c
}

// InsertLeaveApplication provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) InsertLeaveApplication(ctx context.Context, tx *sql.Tx, p param.LeaveApplicationParam) (int64, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertLeaveApplication")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.LeaveApplicationParam) (int64, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.LeaveApplicationParam) int64); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.LeaveApplicationParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILeaveRepo_InsertLeaveApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLeaveApplication'
type MockILeaveRepo_InsertLeaveApplication_Call struct {
	*mock.Call
}

// InsertLeaveApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.LeaveApplicationParam
func (_e *MockILeaveRepo_Expecter) InsertLeaveApplication(ctx interface{}, tx interface{}, p interface{}) *MockILeaveRepo_InsertLeaveApplication_Call {
	return &MockILeaveRepo_InsertLeaveApplication_Call{Call: _e.mock.On("InsertLeaveApplication", ctx, tx, p)}
}

func (_c *MockILeaveRepo_InsertLeaveApplication_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.LeaveApplicationParam)) *MockILeaveRepo_InsertLeaveApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.LeaveApplicationParam
		if args[2] != nil {
			arg2 = args[2].(param.LeaveApplicationParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_InsertLeaveApplication_Call) Return(n int64, err error) *MockILeaveRepo_InsertLeaveApplication_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockILeaveRepo_InsertLeaveApplication_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.LeaveApplicationParam) (int64, error)) *MockILeaveRepo_InsertLeaveApplication_Call {
	_c.Call.Return(run)
	return _c
}

// IsStaffOnLeave provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) IsStaffOnLeave(ctx context.Context, staffID int64, date string) (bool, error) {
	ret := _mock.Called(ctx, staffID, date)

	if len(ret) == 0 {
		panic("no return value specified for IsStaffOnLeave")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return returnFunc(ctx, staffID, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = returnFunc(ctx, staffID, date)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, staffID, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILeaveRepo_IsStaffOnLeave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStaffOnLeave'
type MockILeaveRepo_IsStaffOnLeave_Call struct {
	*mock.Call
}

// IsStaffOnLeave is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int64
//   - date string
func (_e *MockILeaveRepo_Expecter) IsStaffOnLeave(ctx interface{}, staffID interface{}, date interface{}) *MockILeaveRepo_IsStaffOnLeave_Call {
	return &MockILeaveRepo_IsStaffOnLeave_Call{Call: _e.mock.On("IsStaffOnLeave", ctx, staffID, date)}
}

func (_c *MockILeaveRepo_IsStaffOnLeave_Call) Run(run func(ctx context.Context, staffID int64, date string)) *MockILeaveRepo_IsStaffOnLeave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_IsStaffOnLeave_Call) Return(b bool, err error) *MockILeaveRepo_IsStaffOnLeave_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockILeaveRepo_IsStaffOnLeave_Call) RunAndReturn(run func(ctx context.Context, staffID int64, date string) (bool, error)) *MockILeaveRepo_IsStaffOnLeave_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteLeaveApplication provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) SoftDeleteLeaveApplication(ctx context.Context, tx *sql.Tx, leaveID int64) error {
	ret := _mock.Called(ctx, tx, leaveID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteLeaveApplication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64) error); ok {
		r0 = returnFunc(ctx, tx, leaveID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILeaveRepo_SoftDeleteLeaveApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteLeaveApplication'
type MockILeaveRepo_SoftDeleteLeaveApplication_Call struct {
	*mock.Call
}

// SoftDeleteLeaveApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - leaveID int64
func (_e *MockILeaveRepo_Expecter) SoftDeleteLeaveApplication(ctx interface{}, tx interface{}, leaveID interface{}) *MockILeaveRepo_SoftDeleteLeaveApplication_Call {
	return &MockILeaveRepo_SoftDeleteLeaveApplication_Call{Call: _e.mock.On("SoftDeleteLeaveApplication", ctx, tx, leaveID)}
}

func (_c *MockILeaveRepo_SoftDeleteLeaveApplication_Call) Run(run func(ctx context.Context, tx *sql.Tx, leaveID int64)) *MockILeaveRepo_SoftDeleteLeaveApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_SoftDeleteLeaveApplication_Call) Return(err error) *MockILeaveRepo_SoftDeleteLeaveApplication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILeaveRepo_SoftDeleteLeaveApplication_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, leaveID int64) error) *MockILeaveRepo_SoftDeleteLeaveApplication_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLeaveJustification provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) UpdateLeaveJustification(ctx context.Context, tx *sql.Tx, leaveID int64, justification *string) error {
	ret := _mock.Called(ctx, tx, leaveID, justification)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLeaveJustification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, *string) error); ok {
		r0 = returnFunc(ctx, tx, leaveID, justification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILeaveRepo_UpdateLeaveJustification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLeaveJustification'
type MockILeaveRepo_UpdateLeaveJustification_Call struct {
	*mock.Call
}

// UpdateLeaveJustification is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - leaveID int64
//   - justification *string
func (_e *MockILeaveRepo_Expecter) UpdateLeaveJustification(ctx interface{}, tx interface{}, leaveID interface{}, justification interface{}) *MockILeaveRepo_UpdateLeaveJustification_Call {
	return &MockILeaveRepo_UpdateLeaveJustification_Call{Call: _e.mock.On("UpdateLeaveJustification", ctx, tx, leaveID, justification)}
}

func (_c *MockILeaveRepo_UpdateLeaveJustification_Call) Run(run func(ctx context.Context, tx *sql.Tx, leaveID int64, justification *string)) *MockILeaveRepo_UpdateLeaveJustification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_UpdateLeaveJustification_Call) Return(err error) *MockILeaveRepo_UpdateLeaveJustification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILeaveRepo_UpdateLeaveJustification_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, leaveID int64, justification *string) error) *MockILeaveRepo_UpdateLeaveJustification_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLeaveStatus provides a mock function for the type MockILeaveRepo
func (_mock *MockILeaveRepo) UpdateLeaveStatus(ctx context.Context, tx *sql.Tx, leaveID int64, status string, remark *string) error {
	ret := _mock.Called(ctx, tx, leaveID, status, remark)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLeaveStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, string, *string) error); ok {
		r0 = returnFunc(ctx, tx, leaveID, status, remark)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILeaveRepo_UpdateLeaveStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLeaveStatus'
type MockILeaveRepo_UpdateLeaveStatus_Call struct {
	*mock.Call
}

// UpdateLeaveStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - leaveID int64
//   - status string
//   - remark *string
func (_e *MockILeaveRepo_Expecter) UpdateLeaveStatus(ctx interface{}, tx interface{}, leaveID interface{}, status interface{}, remark interface{}) *MockILeaveRepo_UpdateLeaveStatus_Call {
	return &MockILeaveRepo_UpdateLeaveStatus_Call{Call: _e.mock.On("UpdateLeaveStatus", ctx, tx, leaveID, status, remark)}
}

func (_c *MockILeaveRepo_UpdateLeaveStatus_Call) Run(run func(ctx context.Context, tx *sql.Tx, leaveID int64, status string, remark *string)) *MockILeaveRepo_UpdateLeaveStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockILeaveRepo_UpdateLeaveStatus_Call) Return(err error) *MockILeaveRepo_UpdateLeaveStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILeaveRepo_UpdateLeaveStatus_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, leaveID int64, status string, remark *string) error) *MockILeaveRepo_UpdateLeaveStatus_Call {
	_c.Call.Return(run)
	return _c
}
