// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIEmailService creates a new instance of MockIEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEmailService {
	mock := &MockIEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIEmailService is an autogenerated mock type for the IEmailService type
type MockIEmailService struct {
	mock.Mock
}

type MockIEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEmailService) EXPECT() *MockIEmailService_Expecter {
	return &MockIEmailService_Expecter{mock: &_m.Mock}
}

// SendStaffWelcomeEmail provides a mock function for the type MockIEmailService
func (_mock *MockIEmailService) SendStaffWelcomeEmail(toEmail string, tempPassword string) error {
	ret := _mock.Called(toEmail, tempPassword)

	if len(ret) == 0 {
		panic("no return value specified for SendStaffWelcomeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(toEmail, tempPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmailService_SendStaffWelcomeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStaffWelcomeEmail'
type MockIEmailService_SendStaffWelcomeEmail_Call struct {
	*mock.Call
}

// SendStaffWelcomeEmail is a helper method to define mock.On call
//   - toEmail string
//   - tempPassword string
func (_e *MockIEmailService_Expecter) SendStaffWelcomeEmail(toEmail interface{}, tempPassword interface{}) *MockIEmailService_SendStaffWelcomeEmail_Call {
	return &MockIEmailService_SendStaffWelcomeEmail_Call{Call: _e.mock.On("SendStaffWelcomeEmail", toEmail, tempPassword)}
}

func (_c *MockIEmailService_SendStaffWelcomeEmail_Call) Run(run func(toEmail string, tempPassword string)) *MockIEmailService_SendStaffWelcomeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEmailService_SendStaffWelcomeEmail_Call) Return(err error) *MockIEmailService_SendStaffWelcomeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmailService_SendStaffWelcomeEmail_Call) RunAndReturn(run func(toEmail string, tempPassword string) error) *MockIEmailService_SendStaffWelcomeEmail_Call {
	_c.Call.Return(run)
	return _c
}
