// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"fyp/domain/param"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIServiceSlotRepo creates a new instance of MockIServiceSlotRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServiceSlotRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServiceSlotRepo {
	mock := &MockIServiceSlotRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIServiceSlotRepo is an autogenerated mock type for the IServiceSlotRepo type
type MockIServiceSlotRepo struct {
	mock.Mock
}

type MockIServiceSlotRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServiceSlotRepo) EXPECT() *MockIServiceSlotRepo_Expecter {
	return &MockIServiceSlotRepo_Expecter{mock: &_m.Mock}
}

// GetAvailableStaff provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) GetAvailableStaff(ctx context.Context, businessID int64, date string, weekday string, startTime time.Time, endTime time.Time, excludeSlotID int64) ([]param.StaffParam, error) {
	ret := _mock.Called(ctx, businessID, date, weekday, startTime, endTime, excludeSlotID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableStaff")
	}

	var r0 []param.StaffParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, time.Time, time.Time, int64) ([]param.StaffParam, error)); ok {
		return returnFunc(ctx, businessID, date, weekday, startTime, endTime, excludeSlotID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, time.Time, time.Time, int64) []param.StaffParam); ok {
		r0 = returnFunc(ctx, businessID, date, weekday, startTime, endTime, excludeSlotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.StaffParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, time.Time, time.Time, int64) error); ok {
		r1 = returnFunc(ctx, businessID, date, weekday, startTime, endTime, excludeSlotID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_GetAvailableStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableStaff'
type MockIServiceSlotRepo_GetAvailableStaff_Call struct {
	*mock.Call
}

// GetAvailableStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - date string
//   - weekday string
//   - startTime time.Time
//   - endTime time.Time
//   - excludeSlotID int64
func (_e *MockIServiceSlotRepo_Expecter) GetAvailableStaff(ctx interface{}, businessID interface{}, date interface{}, weekday interface{}, startTime interface{}, endTime interface{}, excludeSlotID interface{}) *MockIServiceSlotRepo_GetAvailableStaff_Call {
	return &MockIServiceSlotRepo_GetAvailableStaff_Call{Call: _e.mock.On("GetAvailableStaff", ctx, businessID, date, weekday, startTime, endTime, excludeSlotID)}
}

func (_c *MockIServiceSlotRepo_GetAvailableStaff_Call) Run(run func(ctx context.Context, businessID int64, date string, weekday string, startTime time.Time, endTime time.Time, excludeSlotID int64)) *MockIServiceSlotRepo_GetAvailableStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		var arg6 int64
		if args[6] != nil {
			arg6 = args[6].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_GetAvailableStaff_Call) Return(staffParams []param.StaffParam, err error) *MockIServiceSlotRepo_GetAvailableStaff_Call {
	_c.Call.Return(staffParams, err)
	return _c
}

func (_c *MockIServiceSlotRepo_GetAvailableStaff_Call) RunAndReturn(run func(ctx context.Context, businessID int64, date string, weekday string, startTime time.Time, endTime time.Time, excludeSlotID int64) ([]param.StaffParam, error)) *MockIServiceSlotRepo_GetAvailableStaff_Call {
	_c.Call.Return(run)
	return _c
}

// GetFutureRecurringSlotIDs provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) GetFutureRecurringSlotIDs(ctx context.Context, businessID int64, staffID *int64, startTime time.Time, endTime time.Time, fromDate string) ([]int64, error) {
	ret := _mock.Called(ctx, businessID, staffID, startTime, endTime, fromDate)

	if len(ret) == 0 {
		panic("no return value specified for GetFutureRecurringSlotIDs")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64, time.Time, time.Time, string) ([]int64, error)); ok {
		return returnFunc(ctx, businessID, staffID, startTime, endTime, fromDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64, time.Time, time.Time, string) []int64); ok {
		r0 = returnFunc(ctx, businessID, staffID, startTime, endTime, fromDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *int64, time.Time, time.Time, string) error); ok {
		r1 = returnFunc(ctx, businessID, staffID, startTime, endTime, fromDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFutureRecurringSlotIDs'
type MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call struct {
	*mock.Call
}

// GetFutureRecurringSlotIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - staffID *int64
//   - startTime time.Time
//   - endTime time.Time
//   - fromDate string
func (_e *MockIServiceSlotRepo_Expecter) GetFutureRecurringSlotIDs(ctx interface{}, businessID interface{}, staffID interface{}, startTime interface{}, endTime interface{}, fromDate interface{}) *MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call {
	return &MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call{Call: _e.mock.On("GetFutureRecurringSlotIDs", ctx, businessID, staffID, startTime, endTime, fromDate)}
}

func (_c *MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call) Run(run func(ctx context.Context, businessID int64, staffID *int64, startTime time.Time, endTime time.Time, fromDate string)) *MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call) Return(int64s []int64, err error) *MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call) RunAndReturn(run func(ctx context.Context, businessID int64, staffID *int64, startTime time.Time, endTime time.Time, fromDate string) ([]int64, error)) *MockIServiceSlotRepo_GetFutureRecurringSlotIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceSlotByID provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) GetServiceSlotByID(ctx context.Context, serviceSlotID int64, businessID int64) (*param.ServiceSlotParam, error) {
	ret := _mock.Called(ctx, serviceSlotID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceSlotByID")
	}

	var r0 *param.ServiceSlotParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*param.ServiceSlotParam, error)); ok {
		return returnFunc(ctx, serviceSlotID, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *param.ServiceSlotParam); ok {
		r0 = returnFunc(ctx, serviceSlotID, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.ServiceSlotParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, serviceSlotID, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_GetServiceSlotByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceSlotByID'
type MockIServiceSlotRepo_GetServiceSlotByID_Call struct {
	*mock.Call
}

// GetServiceSlotByID is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceSlotID int64
//   - businessID int64
func (_e *MockIServiceSlotRepo_Expecter) GetServiceSlotByID(ctx interface{}, serviceSlotID interface{}, businessID interface{}) *MockIServiceSlotRepo_GetServiceSlotByID_Call {
	return &MockIServiceSlotRepo_GetServiceSlotByID_Call{Call: _e.mock.On("GetServiceSlotByID", ctx, serviceSlotID, businessID)}
}

func (_c *MockIServiceSlotRepo_GetServiceSlotByID_Call) Run(run func(ctx context.Context, serviceSlotID int64, businessID int64)) *MockIServiceSlotRepo_GetServiceSlotByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_GetServiceSlotByID_Call) Return(serviceSlotParam *param.ServiceSlotParam, err error) *MockIServiceSlotRepo_GetServiceSlotByID_Call {
	_c.Call.Return(serviceSlotParam, err)
	return _c
}

func (_c *MockIServiceSlotRepo_GetServiceSlotByID_Call) RunAndReturn(run func(ctx context.Context, serviceSlotID int64, businessID int64) (*param.ServiceSlotParam, error)) *MockIServiceSlotRepo_GetServiceSlotByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceSlotsByBusinessAndDate provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) GetServiceSlotsByBusinessAndDate(ctx context.Context, businessID int64, date string, staffID *int64, serviceID *int64, unassignedOnly bool) ([]param.ServiceSlotParam, error) {
	ret := _mock.Called(ctx, businessID, date, staffID, serviceID, unassignedOnly)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceSlotsByBusinessAndDate")
	}

	var r0 []param.ServiceSlotParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, *int64, *int64, bool) ([]param.ServiceSlotParam, error)); ok {
		return returnFunc(ctx, businessID, date, staffID, serviceID, unassignedOnly)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, *int64, *int64, bool) []param.ServiceSlotParam); ok {
		r0 = returnFunc(ctx, businessID, date, staffID, serviceID, unassignedOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceSlotParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, *int64, *int64, bool) error); ok {
		r1 = returnFunc(ctx, businessID, date, staffID, serviceID, unassignedOnly)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceSlotsByBusinessAndDate'
type MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call struct {
	*mock.Call
}

// GetServiceSlotsByBusinessAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - date string
//   - staffID *int64
//   - serviceID *int64
//   - unassignedOnly bool
func (_e *MockIServiceSlotRepo_Expecter) GetServiceSlotsByBusinessAndDate(ctx interface{}, businessID interface{}, date interface{}, staffID interface{}, serviceID interface{}, unassignedOnly interface{}) *MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call {
	return &MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call{Call: _e.mock.On("GetServiceSlotsByBusinessAndDate", ctx, businessID, date, staffID, serviceID, unassignedOnly)}
}

func (_c *MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call) Run(run func(ctx context.Context, businessID int64, date string, staffID *int64, serviceID *int64, unassignedOnly bool)) *MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call) Return(serviceSlotParams []param.ServiceSlotParam, err error) *MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call {
	_c.Call.Return(serviceSlotParams, err)
	return _c
}

func (_c *MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call) RunAndReturn(run func(ctx context.Context, businessID int64, date string, staffID *int64, serviceID *int64, unassignedOnly bool) ([]param.ServiceSlotParam, error)) *MockIServiceSlotRepo_GetServiceSlotsByBusinessAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRecurringSchedule provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) InsertRecurringSchedule(ctx context.Context, tx *sql.Tx, p param.ServiceSlotParam, servicePackageID int64, day string) error {
	ret := _mock.Called(ctx, tx, p, servicePackageID, day)

	if len(ret) == 0 {
		panic("no return value specified for InsertRecurringSchedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceSlotParam, int64, string) error); ok {
		r0 = returnFunc(ctx, tx, p, servicePackageID, day)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceSlotRepo_InsertRecurringSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRecurringSchedule'
type MockIServiceSlotRepo_InsertRecurringSchedule_Call struct {
	*mock.Call
}

// InsertRecurringSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServiceSlotParam
//   - servicePackageID int64
//   - day string
func (_e *MockIServiceSlotRepo_Expecter) InsertRecurringSchedule(ctx interface{}, tx interface{}, p interface{}, servicePackageID interface{}, day interface{}) *MockIServiceSlotRepo_InsertRecurringSchedule_Call {
	return &MockIServiceSlotRepo_InsertRecurringSchedule_Call{Call: _e.mock.On("InsertRecurringSchedule", ctx, tx, p, servicePackageID, day)}
}

func (_c *MockIServiceSlotRepo_InsertRecurringSchedule_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServiceSlotParam, servicePackageID int64, day string)) *MockIServiceSlotRepo_InsertRecurringSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServiceSlotParam
		if args[2] != nil {
			arg2 = args[2].(param.ServiceSlotParam)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_InsertRecurringSchedule_Call) Return(err error) *MockIServiceSlotRepo_InsertRecurringSchedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceSlotRepo_InsertRecurringSchedule_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServiceSlotParam, servicePackageID int64, day string) error) *MockIServiceSlotRepo_InsertRecurringSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// InsertServiceSlot provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) InsertServiceSlot(ctx context.Context, tx *sql.Tx, p param.ServiceSlotParam) (int64, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertServiceSlot")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceSlotParam) (int64, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceSlotParam) int64); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.ServiceSlotParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_InsertServiceSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertServiceSlot'
type MockIServiceSlotRepo_InsertServiceSlot_Call struct {
	*mock.Call
}

// InsertServiceSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServiceSlotParam
func (_e *MockIServiceSlotRepo_Expecter) InsertServiceSlot(ctx interface{}, tx interface{}, p interface{}) *MockIServiceSlotRepo_InsertServiceSlot_Call {
	return &MockIServiceSlotRepo_InsertServiceSlot_Call{Call: _e.mock.On("InsertServiceSlot", ctx, tx, p)}
}

func (_c *MockIServiceSlotRepo_InsertServiceSlot_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServiceSlotParam)) *MockIServiceSlotRepo_InsertServiceSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServiceSlotParam
		if args[2] != nil {
			arg2 = args[2].(param.ServiceSlotParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_InsertServiceSlot_Call) Return(n int64, err error) *MockIServiceSlotRepo_InsertServiceSlot_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIServiceSlotRepo_InsertServiceSlot_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServiceSlotParam) (int64, error)) *MockIServiceSlotRepo_InsertServiceSlot_Call {
	_c.Call.Return(run)
	return _c
}

// InsertServiceSlotPackage provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) InsertServiceSlotPackage(ctx context.Context, tx *sql.Tx, serviceSlotID int64, servicePackageID int64) error {
	ret := _mock.Called(ctx, tx, serviceSlotID, servicePackageID)

	if len(ret) == 0 {
		panic("no return value specified for InsertServiceSlotPackage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64) error); ok {
		r0 = returnFunc(ctx, tx, serviceSlotID, servicePackageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceSlotRepo_InsertServiceSlotPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertServiceSlotPackage'
type MockIServiceSlotRepo_InsertServiceSlotPackage_Call struct {
	*mock.Call
}

// InsertServiceSlotPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - serviceSlotID int64
//   - servicePackageID int64
func (_e *MockIServiceSlotRepo_Expecter) InsertServiceSlotPackage(ctx interface{}, tx interface{}, serviceSlotID interface{}, servicePackageID interface{}) *MockIServiceSlotRepo_InsertServiceSlotPackage_Call {
	return &MockIServiceSlotRepo_InsertServiceSlotPackage_Call{Call: _e.mock.On("InsertServiceSlotPackage", ctx, tx, serviceSlotID, servicePackageID)}
}

func (_c *MockIServiceSlotRepo_InsertServiceSlotPackage_Call) Run(run func(ctx context.Context, tx *sql.Tx, serviceSlotID int64, servicePackageID int64)) *MockIServiceSlotRepo_InsertServiceSlotPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_InsertServiceSlotPackage_Call) Return(err error) *MockIServiceSlotRepo_InsertServiceSlotPackage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceSlotRepo_InsertServiceSlotPackage_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, serviceSlotID int64, servicePackageID int64) error) *MockIServiceSlotRepo_InsertServiceSlotPackage_Call {
	_c.Call.Return(run)
	return _c
}

// PackagesBelongToBusiness provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) PackagesBelongToBusiness(ctx context.Context, businessID int64, packageIDs []int64) (bool, error) {
	ret := _mock.Called(ctx, businessID, packageIDs)

	if len(ret) == 0 {
		panic("no return value specified for PackagesBelongToBusiness")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []int64) (bool, error)); ok {
		return returnFunc(ctx, businessID, packageIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []int64) bool); ok {
		r0 = returnFunc(ctx, businessID, packageIDs)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, []int64) error); ok {
		r1 = returnFunc(ctx, businessID, packageIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_PackagesBelongToBusiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PackagesBelongToBusiness'
type MockIServiceSlotRepo_PackagesBelongToBusiness_Call struct {
	*mock.Call
}

// PackagesBelongToBusiness is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - packageIDs []int64
func (_e *MockIServiceSlotRepo_Expecter) PackagesBelongToBusiness(ctx interface{}, businessID interface{}, packageIDs interface{}) *MockIServiceSlotRepo_PackagesBelongToBusiness_Call {
	return &MockIServiceSlotRepo_PackagesBelongToBusiness_Call{Call: _e.mock.On("PackagesBelongToBusiness", ctx, businessID, packageIDs)}
}

func (_c *MockIServiceSlotRepo_PackagesBelongToBusiness_Call) Run(run func(ctx context.Context, businessID int64, packageIDs []int64)) *MockIServiceSlotRepo_PackagesBelongToBusiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []int64
		if args[2] != nil {
			arg2 = args[2].([]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_PackagesBelongToBusiness_Call) Return(b bool, err error) *MockIServiceSlotRepo_PackagesBelongToBusiness_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIServiceSlotRepo_PackagesBelongToBusiness_Call) RunAndReturn(run func(ctx context.Context, businessID int64, packageIDs []int64) (bool, error)) *MockIServiceSlotRepo_PackagesBelongToBusiness_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignStaff provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) ReassignStaff(ctx context.Context, tx *sql.Tx, serviceSlotID int64, businessID int64, staffID *int64) error {
	ret := _mock.Called(ctx, tx, serviceSlotID, businessID, staffID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignStaff")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64, *int64) error); ok {
		r0 = returnFunc(ctx, tx, serviceSlotID, businessID, staffID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceSlotRepo_ReassignStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignStaff'
type MockIServiceSlotRepo_ReassignStaff_Call struct {
	*mock.Call
}

// ReassignStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - serviceSlotID int64
//   - businessID int64
//   - staffID *int64
func (_e *MockIServiceSlotRepo_Expecter) ReassignStaff(ctx interface{}, tx interface{}, serviceSlotID interface{}, businessID interface{}, staffID interface{}) *MockIServiceSlotRepo_ReassignStaff_Call {
	return &MockIServiceSlotRepo_ReassignStaff_Call{Call: _e.mock.On("ReassignStaff", ctx, tx, serviceSlotID, businessID, staffID)}
}

func (_c *MockIServiceSlotRepo_ReassignStaff_Call) Run(run func(ctx context.Context, tx *sql.Tx, serviceSlotID int64, businessID int64, staffID *int64)) *MockIServiceSlotRepo_ReassignStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_ReassignStaff_Call) Return(err error) *MockIServiceSlotRepo_ReassignStaff_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceSlotRepo_ReassignStaff_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, serviceSlotID int64, businessID int64, staffID *int64) error) *MockIServiceSlotRepo_ReassignStaff_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteRecurringSchedules provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) SoftDeleteRecurringSchedules(ctx context.Context, tx *sql.Tx, businessID int64, staffID int64, weekday string, startTime time.Time, endTime time.Time) error {
	ret := _mock.Called(ctx, tx, businessID, staffID, weekday, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteRecurringSchedules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64, string, time.Time, time.Time) error); ok {
		r0 = returnFunc(ctx, tx, businessID, staffID, weekday, startTime, endTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteRecurringSchedules'
type MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call struct {
	*mock.Call
}

// SoftDeleteRecurringSchedules is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - businessID int64
//   - staffID int64
//   - weekday string
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockIServiceSlotRepo_Expecter) SoftDeleteRecurringSchedules(ctx interface{}, tx interface{}, businessID interface{}, staffID interface{}, weekday interface{}, startTime interface{}, endTime interface{}) *MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call {
	return &MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call{Call: _e.mock.On("SoftDeleteRecurringSchedules", ctx, tx, businessID, staffID, weekday, startTime, endTime)}
}

func (_c *MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call) Run(run func(ctx context.Context, tx *sql.Tx, businessID int64, staffID int64, weekday string, startTime time.Time, endTime time.Time)) *MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call) Return(err error) *MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, businessID int64, staffID int64, weekday string, startTime time.Time, endTime time.Time) error) *MockIServiceSlotRepo_SoftDeleteRecurringSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteServiceSlot provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) SoftDeleteServiceSlot(ctx context.Context, tx *sql.Tx, serviceSlotID int64, businessID int64) error {
	ret := _mock.Called(ctx, tx, serviceSlotID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteServiceSlot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64) error); ok {
		r0 = returnFunc(ctx, tx, serviceSlotID, businessID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceSlotRepo_SoftDeleteServiceSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteServiceSlot'
type MockIServiceSlotRepo_SoftDeleteServiceSlot_Call struct {
	*mock.Call
}

// SoftDeleteServiceSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - serviceSlotID int64
//   - businessID int64
func (_e *MockIServiceSlotRepo_Expecter) SoftDeleteServiceSlot(ctx interface{}, tx interface{}, serviceSlotID interface{}, businessID interface{}) *MockIServiceSlotRepo_SoftDeleteServiceSlot_Call {
	return &MockIServiceSlotRepo_SoftDeleteServiceSlot_Call{Call: _e.mock.On("SoftDeleteServiceSlot", ctx, tx, serviceSlotID, businessID)}
}

func (_c *MockIServiceSlotRepo_SoftDeleteServiceSlot_Call) Run(run func(ctx context.Context, tx *sql.Tx, serviceSlotID int64, businessID int64)) *MockIServiceSlotRepo_SoftDeleteServiceSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_SoftDeleteServiceSlot_Call) Return(err error) *MockIServiceSlotRepo_SoftDeleteServiceSlot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceSlotRepo_SoftDeleteServiceSlot_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, serviceSlotID int64, businessID int64) error) *MockIServiceSlotRepo_SoftDeleteServiceSlot_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteServiceSlots provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) SoftDeleteServiceSlots(ctx context.Context, tx *sql.Tx, slotIDs []int64, businessID int64) error {
	ret := _mock.Called(ctx, tx, slotIDs, businessID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteServiceSlots")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, []int64, int64) error); ok {
		r0 = returnFunc(ctx, tx, slotIDs, businessID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceSlotRepo_SoftDeleteServiceSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteServiceSlots'
type MockIServiceSlotRepo_SoftDeleteServiceSlots_Call struct {
	*mock.Call
}

// SoftDeleteServiceSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - slotIDs []int64
//   - businessID int64
func (_e *MockIServiceSlotRepo_Expecter) SoftDeleteServiceSlots(ctx interface{}, tx interface{}, slotIDs interface{}, businessID interface{}) *MockIServiceSlotRepo_SoftDeleteServiceSlots_Call {
	return &MockIServiceSlotRepo_SoftDeleteServiceSlots_Call{Call: _e.mock.On("SoftDeleteServiceSlots", ctx, tx, slotIDs, businessID)}
}

func (_c *MockIServiceSlotRepo_SoftDeleteServiceSlots_Call) Run(run func(ctx context.Context, tx *sql.Tx, slotIDs []int64, businessID int64)) *MockIServiceSlotRepo_SoftDeleteServiceSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 []int64
		if args[2] != nil {
			arg2 = args[2].([]int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_SoftDeleteServiceSlots_Call) Return(err error) *MockIServiceSlotRepo_SoftDeleteServiceSlots_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceSlotRepo_SoftDeleteServiceSlots_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, slotIDs []int64, businessID int64) error) *MockIServiceSlotRepo_SoftDeleteServiceSlots_Call {
	_c.Call.Return(run)
	return _c
}

// StaffBelongsToBusiness provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) StaffBelongsToBusiness(ctx context.Context, staffID int64, businessID int64) (bool, error) {
	ret := _mock.Called(ctx, staffID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for StaffBelongsToBusiness")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return returnFunc(ctx, staffID, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = returnFunc(ctx, staffID, businessID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, staffID, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_StaffBelongsToBusiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaffBelongsToBusiness'
type MockIServiceSlotRepo_StaffBelongsToBusiness_Call struct {
	*mock.Call
}

// StaffBelongsToBusiness is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int64
//   - businessID int64
func (_e *MockIServiceSlotRepo_Expecter) StaffBelongsToBusiness(ctx interface{}, staffID interface{}, businessID interface{}) *MockIServiceSlotRepo_StaffBelongsToBusiness_Call {
	return &MockIServiceSlotRepo_StaffBelongsToBusiness_Call{Call: _e.mock.On("StaffBelongsToBusiness", ctx, staffID, businessID)}
}

func (_c *MockIServiceSlotRepo_StaffBelongsToBusiness_Call) Run(run func(ctx context.Context, staffID int64, businessID int64)) *MockIServiceSlotRepo_StaffBelongsToBusiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_StaffBelongsToBusiness_Call) Return(b bool, err error) *MockIServiceSlotRepo_StaffBelongsToBusiness_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIServiceSlotRepo_StaffBelongsToBusiness_Call) RunAndReturn(run func(ctx context.Context, staffID int64, businessID int64) (bool, error)) *MockIServiceSlotRepo_StaffBelongsToBusiness_Call {
	_c.Call.Return(run)
	return _c
}

// StaffCoversTime provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) StaffCoversTime(ctx context.Context, staffID int64, weekday string, startTime time.Time, endTime time.Time) (bool, error) {
	ret := _mock.Called(ctx, staffID, weekday, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for StaffCoversTime")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, time.Time, time.Time) (bool, error)); ok {
		return returnFunc(ctx, staffID, weekday, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, time.Time, time.Time) bool); ok {
		r0 = returnFunc(ctx, staffID, weekday, startTime, endTime)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, staffID, weekday, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_StaffCoversTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaffCoversTime'
type MockIServiceSlotRepo_StaffCoversTime_Call struct {
	*mock.Call
}

// StaffCoversTime is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int64
//   - weekday string
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockIServiceSlotRepo_Expecter) StaffCoversTime(ctx interface{}, staffID interface{}, weekday interface{}, startTime interface{}, endTime interface{}) *MockIServiceSlotRepo_StaffCoversTime_Call {
	return &MockIServiceSlotRepo_StaffCoversTime_Call{Call: _e.mock.On("StaffCoversTime", ctx, staffID, weekday, startTime, endTime)}
}

func (_c *MockIServiceSlotRepo_StaffCoversTime_Call) Run(run func(ctx context.Context, staffID int64, weekday string, startTime time.Time, endTime time.Time)) *MockIServiceSlotRepo_StaffCoversTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_StaffCoversTime_Call) Return(b bool, err error) *MockIServiceSlotRepo_StaffCoversTime_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIServiceSlotRepo_StaffCoversTime_Call) RunAndReturn(run func(ctx context.Context, staffID int64, weekday string, startTime time.Time, endTime time.Time) (bool, error)) *MockIServiceSlotRepo_StaffCoversTime_Call {
	_c.Call.Return(run)
	return _c
}

// StaffHasOverlappingSlot provides a mock function for the type MockIServiceSlotRepo
func (_mock *MockIServiceSlotRepo) StaffHasOverlappingSlot(ctx context.Context, staffID int64, date string, startTime time.Time, endTime time.Time, excludeSlotID int64) (bool, error) {
	ret := _mock.Called(ctx, staffID, date, startTime, endTime, excludeSlotID)

	if len(ret) == 0 {
		panic("no return value specified for StaffHasOverlappingSlot")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, time.Time, time.Time, int64) (bool, error)); ok {
		return returnFunc(ctx, staffID, date, startTime, endTime, excludeSlotID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, time.Time, time.Time, int64) bool); ok {
		r0 = returnFunc(ctx, staffID, date, startTime, endTime, excludeSlotID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, time.Time, time.Time, int64) error); ok {
		r1 = returnFunc(ctx, staffID, date, startTime, endTime, excludeSlotID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceSlotRepo_StaffHasOverlappingSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaffHasOverlappingSlot'
type MockIServiceSlotRepo_StaffHasOverlappingSlot_Call struct {
	*mock.Call
}

// StaffHasOverlappingSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int64
//   - date string
//   - startTime time.Time
//   - endTime time.Time
//   - excludeSlotID int64
func (_e *MockIServiceSlotRepo_Expecter) StaffHasOverlappingSlot(ctx interface{}, staffID interface{}, date interface{}, startTime interface{}, endTime interface{}, excludeSlotID interface{}) *MockIServiceSlotRepo_StaffHasOverlappingSlot_Call {
	return &MockIServiceSlotRepo_StaffHasOverlappingSlot_Call{Call: _e.mock.On("StaffHasOverlappingSlot", ctx, staffID, date, startTime, endTime, excludeSlotID)}
}

func (_c *MockIServiceSlotRepo_StaffHasOverlappingSlot_Call) Run(run func(ctx context.Context, staffID int64, date string, startTime time.Time, endTime time.Time, excludeSlotID int64)) *MockIServiceSlotRepo_StaffHasOverlappingSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockIServiceSlotRepo_StaffHasOverlappingSlot_Call) Return(b bool, err error) *MockIServiceSlotRepo_StaffHasOverlappingSlot_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIServiceSlotRepo_StaffHasOverlappingSlot_Call) RunAndReturn(run func(ctx context.Context, staffID int64, date string, startTime time.Time, endTime time.Time, excludeSlotID int64) (bool, error)) *MockIServiceSlotRepo_StaffHasOverlappingSlot_Call {
	_c.Call.Return(run)
	return _c
}
