// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIBusinessService creates a new instance of MockIBusinessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBusinessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBusinessService {
	mock := &MockIBusinessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIBusinessService is an autogenerated mock type for the IBusinessService type
type MockIBusinessService struct {
	mock.Mock
}

type MockIBusinessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBusinessService) EXPECT() *MockIBusinessService_Expecter {
	return &MockIBusinessService_Expecter{mock: &_m.Mock}
}

// RegisterBusinessProfile provides a mock function for the type MockIBusinessService
func (_mock *MockIBusinessService) RegisterBusinessProfile(ctx context.Context, param1 param.BusinessProfileParam) (*param.BusinessProfileParam, error) {
	ret := _mock.Called(ctx, param1)

	if len(ret) == 0 {
		panic("no return value specified for RegisterBusinessProfile")
	}

	var r0 *param.BusinessProfileParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, param.BusinessProfileParam) (*param.BusinessProfileParam, error)); ok {
		return returnFunc(ctx, param1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, param.BusinessProfileParam) *param.BusinessProfileParam); ok {
		r0 = returnFunc(ctx, param1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.BusinessProfileParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, param.BusinessProfileParam) error); ok {
		r1 = returnFunc(ctx, param1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBusinessService_RegisterBusinessProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterBusinessProfile'
type MockIBusinessService_RegisterBusinessProfile_Call struct {
	*mock.Call
}

// RegisterBusinessProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - param1 param.BusinessProfileParam
func (_e *MockIBusinessService_Expecter) RegisterBusinessProfile(ctx interface{}, param1 interface{}) *MockIBusinessService_RegisterBusinessProfile_Call {
	return &MockIBusinessService_RegisterBusinessProfile_Call{Call: _e.mock.On("RegisterBusinessProfile", ctx, param1)}
}

func (_c *MockIBusinessService_RegisterBusinessProfile_Call) Run(run func(ctx context.Context, param1 param.BusinessProfileParam)) *MockIBusinessService_RegisterBusinessProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 param.BusinessProfileParam
		if args[1] != nil {
			arg1 = args[1].(param.BusinessProfileParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBusinessService_RegisterBusinessProfile_Call) Return(businessProfileParam *param.BusinessProfileParam, err error) *MockIBusinessService_RegisterBusinessProfile_Call {
	_c.Call.Return(businessProfileParam, err)
	return _c
}

func (_c *MockIBusinessService_RegisterBusinessProfile_Call) RunAndReturn(run func(ctx context.Context, param1 param.BusinessProfileParam) (*param.BusinessProfileParam, error)) *MockIBusinessService_RegisterBusinessProfile_Call {
	_c.Call.Return(run)
	return _c
}
