// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIStaffRepo creates a new instance of MockIStaffRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStaffRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStaffRepo {
	mock := &MockIStaffRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStaffRepo is an autogenerated mock type for the IStaffRepo type
type MockIStaffRepo struct {
	mock.Mock
}

type MockIStaffRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStaffRepo) EXPECT() *MockIStaffRepo_Expecter {
	return &MockIStaffRepo_Expecter{mock: &_m.Mock}
}

// DeleteStaffWorkingHours provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) DeleteStaffWorkingHours(ctx context.Context, tx *sql.Tx, staffID int64) error {
	ret := _mock.Called(ctx, tx, staffID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStaffWorkingHours")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64) error); ok {
		r0 = returnFunc(ctx, tx, staffID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStaffRepo_DeleteStaffWorkingHours_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStaffWorkingHours'
type MockIStaffRepo_DeleteStaffWorkingHours_Call struct {
	*mock.Call
}

// DeleteStaffWorkingHours is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - staffID int64
func (_e *MockIStaffRepo_Expecter) DeleteStaffWorkingHours(ctx interface{}, tx interface{}, staffID interface{}) *MockIStaffRepo_DeleteStaffWorkingHours_Call {
	return &MockIStaffRepo_DeleteStaffWorkingHours_Call{Call: _e.mock.On("DeleteStaffWorkingHours", ctx, tx, staffID)}
}

func (_c *MockIStaffRepo_DeleteStaffWorkingHours_Call) Run(run func(ctx context.Context, tx *sql.Tx, staffID int64)) *MockIStaffRepo_DeleteStaffWorkingHours_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_DeleteStaffWorkingHours_Call) Return(err error) *MockIStaffRepo_DeleteStaffWorkingHours_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStaffRepo_DeleteStaffWorkingHours_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, staffID int64) error) *MockIStaffRepo_DeleteStaffWorkingHours_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaffByBusinessID provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) GetStaffByBusinessID(ctx context.Context, businessID int64) ([]param.StaffParam, error) {
	ret := _mock.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffByBusinessID")
	}

	var r0 []param.StaffParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.StaffParam, error)); ok {
		return returnFunc(ctx, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.StaffParam); ok {
		r0 = returnFunc(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.StaffParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStaffRepo_GetStaffByBusinessID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaffByBusinessID'
type MockIStaffRepo_GetStaffByBusinessID_Call struct {
	*mock.Call
}

// GetStaffByBusinessID is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
func (_e *MockIStaffRepo_Expecter) GetStaffByBusinessID(ctx interface{}, businessID interface{}) *MockIStaffRepo_GetStaffByBusinessID_Call {
	return &MockIStaffRepo_GetStaffByBusinessID_Call{Call: _e.mock.On("GetStaffByBusinessID", ctx, businessID)}
}

func (_c *MockIStaffRepo_GetStaffByBusinessID_Call) Run(run func(ctx context.Context, businessID int64)) *MockIStaffRepo_GetStaffByBusinessID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_GetStaffByBusinessID_Call) Return(staffParams []param.StaffParam, err error) *MockIStaffRepo_GetStaffByBusinessID_Call {
	_c.Call.Return(staffParams, err)
	return _c
}

func (_c *MockIStaffRepo_GetStaffByBusinessID_Call) RunAndReturn(run func(ctx context.Context, businessID int64) ([]param.StaffParam, error)) *MockIStaffRepo_GetStaffByBusinessID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaffByIDTx provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) GetStaffByIDTx(ctx context.Context, tx *sql.Tx, staffID int64, businessID int64) (*param.StaffParam, error) {
	ret := _mock.Called(ctx, tx, staffID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffByIDTx")
	}

	var r0 *param.StaffParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64) (*param.StaffParam, error)); ok {
		return returnFunc(ctx, tx, staffID, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64) *param.StaffParam); ok {
		r0 = returnFunc(ctx, tx, staffID, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.StaffParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, int64, int64) error); ok {
		r1 = returnFunc(ctx, tx, staffID, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStaffRepo_GetStaffByIDTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaffByIDTx'
type MockIStaffRepo_GetStaffByIDTx_Call struct {
	*mock.Call
}

// GetStaffByIDTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - staffID int64
//   - businessID int64
func (_e *MockIStaffRepo_Expecter) GetStaffByIDTx(ctx interface{}, tx interface{}, staffID interface{}, businessID interface{}) *MockIStaffRepo_GetStaffByIDTx_Call {
	return &MockIStaffRepo_GetStaffByIDTx_Call{Call: _e.mock.On("GetStaffByIDTx", ctx, tx, staffID, businessID)}
}

func (_c *MockIStaffRepo_GetStaffByIDTx_Call) Run(run func(ctx context.Context, tx *sql.Tx, staffID int64, businessID int64)) *MockIStaffRepo_GetStaffByIDTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_GetStaffByIDTx_Call) Return(staffParam *param.StaffParam, err error) *MockIStaffRepo_GetStaffByIDTx_Call {
	_c.Call.Return(staffParam, err)
	return _c
}

func (_c *MockIStaffRepo_GetStaffByIDTx_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, staffID int64, businessID int64) (*param.StaffParam, error)) *MockIStaffRepo_GetStaffByIDTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaffByUserID provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) GetStaffByUserID(ctx context.Context, userID int64) (*param.StaffParam, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffByUserID")
	}

	var r0 *param.StaffParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*param.StaffParam, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *param.StaffParam); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.StaffParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStaffRepo_GetStaffByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaffByUserID'
type MockIStaffRepo_GetStaffByUserID_Call struct {
	*mock.Call
}

// GetStaffByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIStaffRepo_Expecter) GetStaffByUserID(ctx interface{}, userID interface{}) *MockIStaffRepo_GetStaffByUserID_Call {
	return &MockIStaffRepo_GetStaffByUserID_Call{Call: _e.mock.On("GetStaffByUserID", ctx, userID)}
}

func (_c *MockIStaffRepo_GetStaffByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockIStaffRepo_GetStaffByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_GetStaffByUserID_Call) Return(staffParam *param.StaffParam, err error) *MockIStaffRepo_GetStaffByUserID_Call {
	_c.Call.Return(staffParam, err)
	return _c
}

func (_c *MockIStaffRepo_GetStaffByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*param.StaffParam, error)) *MockIStaffRepo_GetStaffByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaffWorkingHours provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) GetStaffWorkingHours(ctx context.Context, staffID int64) ([]param.WorkingHourParam, error) {
	ret := _mock.Called(ctx, staffID)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffWorkingHours")
	}

	var r0 []param.WorkingHourParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.WorkingHourParam, error)); ok {
		return returnFunc(ctx, staffID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.WorkingHourParam); ok {
		r0 = returnFunc(ctx, staffID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.WorkingHourParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, staffID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStaffRepo_GetStaffWorkingHours_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaffWorkingHours'
type MockIStaffRepo_GetStaffWorkingHours_Call struct {
	*mock.Call
}

// GetStaffWorkingHours is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int64
func (_e *MockIStaffRepo_Expecter) GetStaffWorkingHours(ctx interface{}, staffID interface{}) *MockIStaffRepo_GetStaffWorkingHours_Call {
	return &MockIStaffRepo_GetStaffWorkingHours_Call{Call: _e.mock.On("GetStaffWorkingHours", ctx, staffID)}
}

func (_c *MockIStaffRepo_GetStaffWorkingHours_Call) Run(run func(ctx context.Context, staffID int64)) *MockIStaffRepo_GetStaffWorkingHours_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_GetStaffWorkingHours_Call) Return(workingHourParams []param.WorkingHourParam, err error) *MockIStaffRepo_GetStaffWorkingHours_Call {
	_c.Call.Return(workingHourParams, err)
	return _c
}

func (_c *MockIStaffRepo_GetStaffWorkingHours_Call) RunAndReturn(run func(ctx context.Context, staffID int64) ([]param.WorkingHourParam, error)) *MockIStaffRepo_GetStaffWorkingHours_Call {
	_c.Call.Return(run)
	return _c
}

// HasBookingForStaff provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) HasBookingForStaff(ctx context.Context, staffID int64) (bool, error) {
	ret := _mock.Called(ctx, staffID)

	if len(ret) == 0 {
		panic("no return value specified for HasBookingForStaff")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, staffID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, staffID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, staffID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStaffRepo_HasBookingForStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBookingForStaff'
type MockIStaffRepo_HasBookingForStaff_Call struct {
	*mock.Call
}

// HasBookingForStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID int64
func (_e *MockIStaffRepo_Expecter) HasBookingForStaff(ctx interface{}, staffID interface{}) *MockIStaffRepo_HasBookingForStaff_Call {
	return &MockIStaffRepo_HasBookingForStaff_Call{Call: _e.mock.On("HasBookingForStaff", ctx, staffID)}
}

func (_c *MockIStaffRepo_HasBookingForStaff_Call) Run(run func(ctx context.Context, staffID int64)) *MockIStaffRepo_HasBookingForStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_HasBookingForStaff_Call) Return(b bool, err error) *MockIStaffRepo_HasBookingForStaff_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIStaffRepo_HasBookingForStaff_Call) RunAndReturn(run func(ctx context.Context, staffID int64) (bool, error)) *MockIStaffRepo_HasBookingForStaff_Call {
	_c.Call.Return(run)
	return _c
}

// InsertStaff provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) InsertStaff(ctx context.Context, tx *sql.Tx, p param.StaffParam) (*int64, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertStaff")
	}

	var r0 *int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.StaffParam) (*int64, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.StaffParam) *int64); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.StaffParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStaffRepo_InsertStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertStaff'
type MockIStaffRepo_InsertStaff_Call struct {
	*mock.Call
}

// InsertStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.StaffParam
func (_e *MockIStaffRepo_Expecter) InsertStaff(ctx interface{}, tx interface{}, p interface{}) *MockIStaffRepo_InsertStaff_Call {
	return &MockIStaffRepo_InsertStaff_Call{Call: _e.mock.On("InsertStaff", ctx, tx, p)}
}

func (_c *MockIStaffRepo_InsertStaff_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.StaffParam)) *MockIStaffRepo_InsertStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.StaffParam
		if args[2] != nil {
			arg2 = args[2].(param.StaffParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_InsertStaff_Call) Return(n *int64, err error) *MockIStaffRepo_InsertStaff_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIStaffRepo_InsertStaff_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.StaffParam) (*int64, error)) *MockIStaffRepo_InsertStaff_Call {
	_c.Call.Return(run)
	return _c
}

// InsertStaffWorkingHours provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) InsertStaffWorkingHours(ctx context.Context, tx *sql.Tx, param1 param.StaffParam) error {
	ret := _mock.Called(ctx, tx, param1)

	if len(ret) == 0 {
		panic("no return value specified for InsertStaffWorkingHours")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.StaffParam) error); ok {
		r0 = returnFunc(ctx, tx, param1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStaffRepo_InsertStaffWorkingHours_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertStaffWorkingHours'
type MockIStaffRepo_InsertStaffWorkingHours_Call struct {
	*mock.Call
}

// InsertStaffWorkingHours is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - param1 param.StaffParam
func (_e *MockIStaffRepo_Expecter) InsertStaffWorkingHours(ctx interface{}, tx interface{}, param1 interface{}) *MockIStaffRepo_InsertStaffWorkingHours_Call {
	return &MockIStaffRepo_InsertStaffWorkingHours_Call{Call: _e.mock.On("InsertStaffWorkingHours", ctx, tx, param1)}
}

func (_c *MockIStaffRepo_InsertStaffWorkingHours_Call) Run(run func(ctx context.Context, tx *sql.Tx, param1 param.StaffParam)) *MockIStaffRepo_InsertStaffWorkingHours_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.StaffParam
		if args[2] != nil {
			arg2 = args[2].(param.StaffParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_InsertStaffWorkingHours_Call) Return(err error) *MockIStaffRepo_InsertStaffWorkingHours_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStaffRepo_InsertStaffWorkingHours_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, param1 param.StaffParam) error) *MockIStaffRepo_InsertStaffWorkingHours_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteStaff provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) SoftDeleteStaff(ctx context.Context, tx *sql.Tx, staffID int64, businessID int64) error {
	ret := _mock.Called(ctx, tx, staffID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteStaff")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64) error); ok {
		r0 = returnFunc(ctx, tx, staffID, businessID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStaffRepo_SoftDeleteStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteStaff'
type MockIStaffRepo_SoftDeleteStaff_Call struct {
	*mock.Call
}

// SoftDeleteStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - staffID int64
//   - businessID int64
func (_e *MockIStaffRepo_Expecter) SoftDeleteStaff(ctx interface{}, tx interface{}, staffID interface{}, businessID interface{}) *MockIStaffRepo_SoftDeleteStaff_Call {
	return &MockIStaffRepo_SoftDeleteStaff_Call{Call: _e.mock.On("SoftDeleteStaff", ctx, tx, staffID, businessID)}
}

func (_c *MockIStaffRepo_SoftDeleteStaff_Call) Run(run func(ctx context.Context, tx *sql.Tx, staffID int64, businessID int64)) *MockIStaffRepo_SoftDeleteStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_SoftDeleteStaff_Call) Return(err error) *MockIStaffRepo_SoftDeleteStaff_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStaffRepo_SoftDeleteStaff_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, staffID int64, businessID int64) error) *MockIStaffRepo_SoftDeleteStaff_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStaff provides a mock function for the type MockIStaffRepo
func (_mock *MockIStaffRepo) UpdateStaff(ctx context.Context, tx *sql.Tx, p param.StaffParam) (*param.StaffParam, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStaff")
	}

	var r0 *param.StaffParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.StaffParam) (*param.StaffParam, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.StaffParam) *param.StaffParam); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.StaffParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.StaffParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStaffRepo_UpdateStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStaff'
type MockIStaffRepo_UpdateStaff_Call struct {
	*mock.Call
}

// UpdateStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.StaffParam
func (_e *MockIStaffRepo_Expecter) UpdateStaff(ctx interface{}, tx interface{}, p interface{}) *MockIStaffRepo_UpdateStaff_Call {
	return &MockIStaffRepo_UpdateStaff_Call{Call: _e.mock.On("UpdateStaff", ctx, tx, p)}
}

func (_c *MockIStaffRepo_UpdateStaff_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.StaffParam)) *MockIStaffRepo_UpdateStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.StaffParam
		if args[2] != nil {
			arg2 = args[2].(param.StaffParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIStaffRepo_UpdateStaff_Call) Return(staffParam *param.StaffParam, err error) *MockIStaffRepo_UpdateStaff_Call {
	_c.Call.Return(staffParam, err)
	return _c
}

func (_c *MockIStaffRepo_UpdateStaff_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.StaffParam) (*param.StaffParam, error)) *MockIStaffRepo_UpdateStaff_Call {
	_c.Call.Return(run)
	return _c
}
