// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAnalyticsService creates a new instance of MockIAnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAnalyticsService {
	mock := &MockIAnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAnalyticsService is an autogenerated mock type for the IAnalyticsService type
type MockIAnalyticsService struct {
	mock.Mock
}

type MockIAnalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAnalyticsService) EXPECT() *MockIAnalyticsService_Expecter {
	return &MockIAnalyticsService_Expecter{mock: &_m.Mock}
}

// GetBookingSummary provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetBookingSummary(ctx context.Context, businessID int64, from string, until string) (*param.BookingSummaryParam, error) {
	ret := _mock.Called(ctx, businessID, from, until)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingSummary")
	}

	var r0 *param.BookingSummaryParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) (*param.BookingSummaryParam, error)); ok {
		return returnFunc(ctx, businessID, from, until)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) *param.BookingSummaryParam); ok {
		r0 = returnFunc(ctx, businessID, from, until)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.BookingSummaryParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, businessID, from, until)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetBookingSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingSummary'
type MockIAnalyticsService_GetBookingSummary_Call struct {
	*mock.Call
}

// GetBookingSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - from string
//   - until string
func (_e *MockIAnalyticsService_Expecter) GetBookingSummary(ctx interface{}, businessID interface{}, from interface{}, until interface{}) *MockIAnalyticsService_GetBookingSummary_Call {
	return &MockIAnalyticsService_GetBookingSummary_Call{Call: _e.mock.On("GetBookingSummary", ctx, businessID, from, until)}
}

func (_c *MockIAnalyticsService_GetBookingSummary_Call) Run(run func(ctx context.Context, businessID int64, from string, until string)) *MockIAnalyticsService_GetBookingSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetBookingSummary_Call) Return(bookingSummaryParam *param.BookingSummaryParam, err error) *MockIAnalyticsService_GetBookingSummary_Call {
	_c.Call.Return(bookingSummaryParam, err)
	return _c
}

func (_c *MockIAnalyticsService_GetBookingSummary_Call) RunAndReturn(run func(ctx context.Context, businessID int64, from string, until string) (*param.BookingSummaryParam, error)) *MockIAnalyticsService_GetBookingSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingTrend provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetBookingTrend(ctx context.Context, businessID int64, from string, until string, granularity string) ([]param.BookingTrendPointParam, error) {
	ret := _mock.Called(ctx, businessID, from, until, granularity)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingTrend")
	}

	var r0 []param.BookingTrendPointParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string) ([]param.BookingTrendPointParam, error)); ok {
		return returnFunc(ctx, businessID, from, until, granularity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string) []param.BookingTrendPointParam); ok {
		r0 = returnFunc(ctx, businessID, from, until, granularity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.BookingTrendPointParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, string) error); ok {
		r1 = returnFunc(ctx, businessID, from, until, granularity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetBookingTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingTrend'
type MockIAnalyticsService_GetBookingTrend_Call struct {
	*mock.Call
}

// GetBookingTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - from string
//   - until string
//   - granularity string
func (_e *MockIAnalyticsService_Expecter) GetBookingTrend(ctx interface{}, businessID interface{}, from interface{}, until interface{}, granularity interface{}) *MockIAnalyticsService_GetBookingTrend_Call {
	return &MockIAnalyticsService_GetBookingTrend_Call{Call: _e.mock.On("GetBookingTrend", ctx, businessID, from, until, granularity)}
}

func (_c *MockIAnalyticsService_GetBookingTrend_Call) Run(run func(ctx context.Context, businessID int64, from string, until string, granularity string)) *MockIAnalyticsService_GetBookingTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetBookingTrend_Call) Return(bookingTrendPointParams []param.BookingTrendPointParam, err error) *MockIAnalyticsService_GetBookingTrend_Call {
	_c.Call.Return(bookingTrendPointParams, err)
	return _c
}

func (_c *MockIAnalyticsService_GetBookingTrend_Call) RunAndReturn(run func(ctx context.Context, businessID int64, from string, until string, granularity string) ([]param.BookingTrendPointParam, error)) *MockIAnalyticsService_GetBookingTrend_Call {
	_c.Call.Return(run)
	return _c
}

// GetBusinessCreatedAt provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetBusinessCreatedAt(ctx context.Context, businessID int64) (string, error) {
	ret := _mock.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetBusinessCreatedAt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (string, error)); ok {
		return returnFunc(ctx, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = returnFunc(ctx, businessID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetBusinessCreatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBusinessCreatedAt'
type MockIAnalyticsService_GetBusinessCreatedAt_Call struct {
	*mock.Call
}

// GetBusinessCreatedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
func (_e *MockIAnalyticsService_Expecter) GetBusinessCreatedAt(ctx interface{}, businessID interface{}) *MockIAnalyticsService_GetBusinessCreatedAt_Call {
	return &MockIAnalyticsService_GetBusinessCreatedAt_Call{Call: _e.mock.On("GetBusinessCreatedAt", ctx, businessID)}
}

func (_c *MockIAnalyticsService_GetBusinessCreatedAt_Call) Run(run func(ctx context.Context, businessID int64)) *MockIAnalyticsService_GetBusinessCreatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetBusinessCreatedAt_Call) Return(s string, err error) *MockIAnalyticsService_GetBusinessCreatedAt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIAnalyticsService_GetBusinessCreatedAt_Call) RunAndReturn(run func(ctx context.Context, businessID int64) (string, error)) *MockIAnalyticsService_GetBusinessCreatedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetCancellationAnalysis provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetCancellationAnalysis(ctx context.Context, businessID int64, from string, until string, staffIDs []int64, serviceIDs []int64) (*param.CancellationAnalysisParam, error) {
	ret := _mock.Called(ctx, businessID, from, until, staffIDs, serviceIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetCancellationAnalysis")
	}

	var r0 *param.CancellationAnalysisParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, []int64, []int64) (*param.CancellationAnalysisParam, error)); ok {
		return returnFunc(ctx, businessID, from, until, staffIDs, serviceIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, []int64, []int64) *param.CancellationAnalysisParam); ok {
		r0 = returnFunc(ctx, businessID, from, until, staffIDs, serviceIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.CancellationAnalysisParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, []int64, []int64) error); ok {
		r1 = returnFunc(ctx, businessID, from, until, staffIDs, serviceIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetCancellationAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCancellationAnalysis'
type MockIAnalyticsService_GetCancellationAnalysis_Call struct {
	*mock.Call
}

// GetCancellationAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - from string
//   - until string
//   - staffIDs []int64
//   - serviceIDs []int64
func (_e *MockIAnalyticsService_Expecter) GetCancellationAnalysis(ctx interface{}, businessID interface{}, from interface{}, until interface{}, staffIDs interface{}, serviceIDs interface{}) *MockIAnalyticsService_GetCancellationAnalysis_Call {
	return &MockIAnalyticsService_GetCancellationAnalysis_Call{Call: _e.mock.On("GetCancellationAnalysis", ctx, businessID, from, until, staffIDs, serviceIDs)}
}

func (_c *MockIAnalyticsService_GetCancellationAnalysis_Call) Run(run func(ctx context.Context, businessID int64, from string, until string, staffIDs []int64, serviceIDs []int64)) *MockIAnalyticsService_GetCancellationAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []int64
		if args[4] != nil {
			arg4 = args[4].([]int64)
		}
		var arg5 []int64
		if args[5] != nil {
			arg5 = args[5].([]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetCancellationAnalysis_Call) Return(cancellationAnalysisParam *param.CancellationAnalysisParam, err error) *MockIAnalyticsService_GetCancellationAnalysis_Call {
	_c.Call.Return(cancellationAnalysisParam, err)
	return _c
}

func (_c *MockIAnalyticsService_GetCancellationAnalysis_Call) RunAndReturn(run func(ctx context.Context, businessID int64, from string, until string, staffIDs []int64, serviceIDs []int64) (*param.CancellationAnalysisParam, error)) *MockIAnalyticsService_GetCancellationAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerRetention provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetCustomerRetention(ctx context.Context, businessID int64, from string, until string) (*param.CustomerRetentionParam, error) {
	ret := _mock.Called(ctx, businessID, from, until)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerRetention")
	}

	var r0 *param.CustomerRetentionParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) (*param.CustomerRetentionParam, error)); ok {
		return returnFunc(ctx, businessID, from, until)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) *param.CustomerRetentionParam); ok {
		r0 = returnFunc(ctx, businessID, from, until)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.CustomerRetentionParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, businessID, from, until)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetCustomerRetention_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerRetention'
type MockIAnalyticsService_GetCustomerRetention_Call struct {
	*mock.Call
}

// GetCustomerRetention is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - from string
//   - until string
func (_e *MockIAnalyticsService_Expecter) GetCustomerRetention(ctx interface{}, businessID interface{}, from interface{}, until interface{}) *MockIAnalyticsService_GetCustomerRetention_Call {
	return &MockIAnalyticsService_GetCustomerRetention_Call{Call: _e.mock.On("GetCustomerRetention", ctx, businessID, from, until)}
}

func (_c *MockIAnalyticsService_GetCustomerRetention_Call) Run(run func(ctx context.Context, businessID int64, from string, until string)) *MockIAnalyticsService_GetCustomerRetention_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetCustomerRetention_Call) Return(customerRetentionParam *param.CustomerRetentionParam, err error) *MockIAnalyticsService_GetCustomerRetention_Call {
	_c.Call.Return(customerRetentionParam, err)
	return _c
}

func (_c *MockIAnalyticsService_GetCustomerRetention_Call) RunAndReturn(run func(ctx context.Context, businessID int64, from string, until string) (*param.CustomerRetentionParam, error)) *MockIAnalyticsService_GetCustomerRetention_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceFilterOptions provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetServiceFilterOptions(ctx context.Context, businessID int64) ([]param.ServiceFilterOptionParam, error) {
	ret := _mock.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceFilterOptions")
	}

	var r0 []param.ServiceFilterOptionParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.ServiceFilterOptionParam, error)); ok {
		return returnFunc(ctx, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.ServiceFilterOptionParam); ok {
		r0 = returnFunc(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceFilterOptionParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetServiceFilterOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceFilterOptions'
type MockIAnalyticsService_GetServiceFilterOptions_Call struct {
	*mock.Call
}

// GetServiceFilterOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
func (_e *MockIAnalyticsService_Expecter) GetServiceFilterOptions(ctx interface{}, businessID interface{}) *MockIAnalyticsService_GetServiceFilterOptions_Call {
	return &MockIAnalyticsService_GetServiceFilterOptions_Call{Call: _e.mock.On("GetServiceFilterOptions", ctx, businessID)}
}

func (_c *MockIAnalyticsService_GetServiceFilterOptions_Call) Run(run func(ctx context.Context, businessID int64)) *MockIAnalyticsService_GetServiceFilterOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetServiceFilterOptions_Call) Return(serviceFilterOptionParams []param.ServiceFilterOptionParam, err error) *MockIAnalyticsService_GetServiceFilterOptions_Call {
	_c.Call.Return(serviceFilterOptionParams, err)
	return _c
}

func (_c *MockIAnalyticsService_GetServiceFilterOptions_Call) RunAndReturn(run func(ctx context.Context, businessID int64) ([]param.ServiceFilterOptionParam, error)) *MockIAnalyticsService_GetServiceFilterOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicePopularity provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetServicePopularity(ctx context.Context, businessID int64, from string, until string) ([]param.ServicePopularityParam, error) {
	ret := _mock.Called(ctx, businessID, from, until)

	if len(ret) == 0 {
		panic("no return value specified for GetServicePopularity")
	}

	var r0 []param.ServicePopularityParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) ([]param.ServicePopularityParam, error)); ok {
		return returnFunc(ctx, businessID, from, until)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) []param.ServicePopularityParam); ok {
		r0 = returnFunc(ctx, businessID, from, until)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServicePopularityParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, businessID, from, until)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetServicePopularity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicePopularity'
type MockIAnalyticsService_GetServicePopularity_Call struct {
	*mock.Call
}

// GetServicePopularity is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - from string
//   - until string
func (_e *MockIAnalyticsService_Expecter) GetServicePopularity(ctx interface{}, businessID interface{}, from interface{}, until interface{}) *MockIAnalyticsService_GetServicePopularity_Call {
	return &MockIAnalyticsService_GetServicePopularity_Call{Call: _e.mock.On("GetServicePopularity", ctx, businessID, from, until)}
}

func (_c *MockIAnalyticsService_GetServicePopularity_Call) Run(run func(ctx context.Context, businessID int64, from string, until string)) *MockIAnalyticsService_GetServicePopularity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetServicePopularity_Call) Return(servicePopularityParams []param.ServicePopularityParam, err error) *MockIAnalyticsService_GetServicePopularity_Call {
	_c.Call.Return(servicePopularityParams, err)
	return _c
}

func (_c *MockIAnalyticsService_GetServicePopularity_Call) RunAndReturn(run func(ctx context.Context, businessID int64, from string, until string) ([]param.ServicePopularityParam, error)) *MockIAnalyticsService_GetServicePopularity_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlotUtilization provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetSlotUtilization(ctx context.Context, businessID int64, from string, until string, groupBy string) (*param.SlotUtilizationParam, error) {
	ret := _mock.Called(ctx, businessID, from, until, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetSlotUtilization")
	}

	var r0 *param.SlotUtilizationParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string) (*param.SlotUtilizationParam, error)); ok {
		return returnFunc(ctx, businessID, from, until, groupBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string) *param.SlotUtilizationParam); ok {
		r0 = returnFunc(ctx, businessID, from, until, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.SlotUtilizationParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, string) error); ok {
		r1 = returnFunc(ctx, businessID, from, until, groupBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetSlotUtilization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlotUtilization'
type MockIAnalyticsService_GetSlotUtilization_Call struct {
	*mock.Call
}

// GetSlotUtilization is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - from string
//   - until string
//   - groupBy string
func (_e *MockIAnalyticsService_Expecter) GetSlotUtilization(ctx interface{}, businessID interface{}, from interface{}, until interface{}, groupBy interface{}) *MockIAnalyticsService_GetSlotUtilization_Call {
	return &MockIAnalyticsService_GetSlotUtilization_Call{Call: _e.mock.On("GetSlotUtilization", ctx, businessID, from, until, groupBy)}
}

func (_c *MockIAnalyticsService_GetSlotUtilization_Call) Run(run func(ctx context.Context, businessID int64, from string, until string, groupBy string)) *MockIAnalyticsService_GetSlotUtilization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetSlotUtilization_Call) Return(slotUtilizationParam *param.SlotUtilizationParam, err error) *MockIAnalyticsService_GetSlotUtilization_Call {
	_c.Call.Return(slotUtilizationParam, err)
	return _c
}

func (_c *MockIAnalyticsService_GetSlotUtilization_Call) RunAndReturn(run func(ctx context.Context, businessID int64, from string, until string, groupBy string) (*param.SlotUtilizationParam, error)) *MockIAnalyticsService_GetSlotUtilization_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaffUtilization provides a mock function for the type MockIAnalyticsService
func (_mock *MockIAnalyticsService) GetStaffUtilization(ctx context.Context, businessID int64, from string, until string) ([]param.StaffUtilizationParam, error) {
	ret := _mock.Called(ctx, businessID, from, until)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffUtilization")
	}

	var r0 []param.StaffUtilizationParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) ([]param.StaffUtilizationParam, error)); ok {
		return returnFunc(ctx, businessID, from, until)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) []param.StaffUtilizationParam); ok {
		r0 = returnFunc(ctx, businessID, from, until)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.StaffUtilizationParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, businessID, from, until)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAnalyticsService_GetStaffUtilization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaffUtilization'
type MockIAnalyticsService_GetStaffUtilization_Call struct {
	*mock.Call
}

// GetStaffUtilization is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
//   - from string
//   - until string
func (_e *MockIAnalyticsService_Expecter) GetStaffUtilization(ctx interface{}, businessID interface{}, from interface{}, until interface{}) *MockIAnalyticsService_GetStaffUtilization_Call {
	return &MockIAnalyticsService_GetStaffUtilization_Call{Call: _e.mock.On("GetStaffUtilization", ctx, businessID, from, until)}
}

func (_c *MockIAnalyticsService_GetStaffUtilization_Call) Run(run func(ctx context.Context, businessID int64, from string, until string)) *MockIAnalyticsService_GetStaffUtilization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIAnalyticsService_GetStaffUtilization_Call) Return(staffUtilizationParams []param.StaffUtilizationParam, err error) *MockIAnalyticsService_GetStaffUtilization_Call {
	_c.Call.Return(staffUtilizationParams, err)
	return _c
}

func (_c *MockIAnalyticsService_GetStaffUtilization_Call) RunAndReturn(run func(ctx context.Context, businessID int64, from string, until string) ([]param.StaffUtilizationParam, error)) *MockIAnalyticsService_GetStaffUtilization_Call {
	_c.Call.Return(run)
	return _c
}
