// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAuthService creates a new instance of MockIAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAuthService {
	mock := &MockIAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAuthService is an autogenerated mock type for the IAuthService type
type MockIAuthService struct {
	mock.Mock
}

type MockIAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAuthService) EXPECT() *MockIAuthService_Expecter {
	return &MockIAuthService_Expecter{mock: &_m.Mock}
}

// LogIn provides a mock function for the type MockIAuthService
func (_mock *MockIAuthService) LogIn(ctx context.Context, logInParam param.LogInParam) (*param.AuthResult, error) {
	ret := _mock.Called(ctx, logInParam)

	if len(ret) == 0 {
		panic("no return value specified for LogIn")
	}

	var r0 *param.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, param.LogInParam) (*param.AuthResult, error)); ok {
		return returnFunc(ctx, logInParam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, param.LogInParam) *param.AuthResult); ok {
		r0 = returnFunc(ctx, logInParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, param.LogInParam) error); ok {
		r1 = returnFunc(ctx, logInParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuthService_LogIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogIn'
type MockIAuthService_LogIn_Call struct {
	*mock.Call
}

// LogIn is a helper method to define mock.On call
//   - ctx context.Context
//   - logInParam param.LogInParam
func (_e *MockIAuthService_Expecter) LogIn(ctx interface{}, logInParam interface{}) *MockIAuthService_LogIn_Call {
	return &MockIAuthService_LogIn_Call{Call: _e.mock.On("LogIn", ctx, logInParam)}
}

func (_c *MockIAuthService_LogIn_Call) Run(run func(ctx context.Context, logInParam param.LogInParam)) *MockIAuthService_LogIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 param.LogInParam
		if args[1] != nil {
			arg1 = args[1].(param.LogInParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAuthService_LogIn_Call) Return(authResult *param.AuthResult, err error) *MockIAuthService_LogIn_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *MockIAuthService_LogIn_Call) RunAndReturn(run func(ctx context.Context, logInParam param.LogInParam) (*param.AuthResult, error)) *MockIAuthService_LogIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockIAuthService
func (_mock *MockIAuthService) SignUp(ctx context.Context, param1 param.SignUpParam) (*param.AuthResult, error) {
	ret := _mock.Called(ctx, param1)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *param.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, param.SignUpParam) (*param.AuthResult, error)); ok {
		return returnFunc(ctx, param1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, param.SignUpParam) *param.AuthResult); ok {
		r0 = returnFunc(ctx, param1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, param.SignUpParam) error); ok {
		r1 = returnFunc(ctx, param1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuthService_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockIAuthService_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - param1 param.SignUpParam
func (_e *MockIAuthService_Expecter) SignUp(ctx interface{}, param1 interface{}) *MockIAuthService_SignUp_Call {
	return &MockIAuthService_SignUp_Call{Call: _e.mock.On("SignUp", ctx, param1)}
}

func (_c *MockIAuthService_SignUp_Call) Run(run func(ctx context.Context, param1 param.SignUpParam)) *MockIAuthService_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 param.SignUpParam
		if args[1] != nil {
			arg1 = args[1].(param.SignUpParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAuthService_SignUp_Call) Return(authResult *param.AuthResult, err error) *MockIAuthService_SignUp_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *MockIAuthService_SignUp_Call) RunAndReturn(run func(ctx context.Context, param1 param.SignUpParam) (*param.AuthResult, error)) *MockIAuthService_SignUp_Call {
	_c.Call.Return(run)
	return _c
}
