// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"fyp/domain/param"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIServiceRepo creates a new instance of MockIServiceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServiceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServiceRepo {
	mock := &MockIServiceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIServiceRepo is an autogenerated mock type for the IServiceRepo type
type MockIServiceRepo struct {
	mock.Mock
}

type MockIServiceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServiceRepo) EXPECT() *MockIServiceRepo_Expecter {
	return &MockIServiceRepo_Expecter{mock: &_m.Mock}
}

// DeleteServicePackagesByServiceID provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) DeleteServicePackagesByServiceID(ctx context.Context, tx *sql.Tx, serviceID int64) error {
	ret := _mock.Called(ctx, tx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServicePackagesByServiceID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64) error); ok {
		r0 = returnFunc(ctx, tx, serviceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceRepo_DeleteServicePackagesByServiceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServicePackagesByServiceID'
type MockIServiceRepo_DeleteServicePackagesByServiceID_Call struct {
	*mock.Call
}

// DeleteServicePackagesByServiceID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - serviceID int64
func (_e *MockIServiceRepo_Expecter) DeleteServicePackagesByServiceID(ctx interface{}, tx interface{}, serviceID interface{}) *MockIServiceRepo_DeleteServicePackagesByServiceID_Call {
	return &MockIServiceRepo_DeleteServicePackagesByServiceID_Call{Call: _e.mock.On("DeleteServicePackagesByServiceID", ctx, tx, serviceID)}
}

func (_c *MockIServiceRepo_DeleteServicePackagesByServiceID_Call) Run(run func(ctx context.Context, tx *sql.Tx, serviceID int64)) *MockIServiceRepo_DeleteServicePackagesByServiceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_DeleteServicePackagesByServiceID_Call) Return(err error) *MockIServiceRepo_DeleteServicePackagesByServiceID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceRepo_DeleteServicePackagesByServiceID_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, serviceID int64) error) *MockIServiceRepo_DeleteServicePackagesByServiceID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPackageItemsByPackageID provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) GetPackageItemsByPackageID(ctx context.Context, servicePackageID int64) ([]param.PackageItemParam, error) {
	ret := _mock.Called(ctx, servicePackageID)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageItemsByPackageID")
	}

	var r0 []param.PackageItemParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.PackageItemParam, error)); ok {
		return returnFunc(ctx, servicePackageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.PackageItemParam); ok {
		r0 = returnFunc(ctx, servicePackageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.PackageItemParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, servicePackageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_GetPackageItemsByPackageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackageItemsByPackageID'
type MockIServiceRepo_GetPackageItemsByPackageID_Call struct {
	*mock.Call
}

// GetPackageItemsByPackageID is a helper method to define mock.On call
//   - ctx context.Context
//   - servicePackageID int64
func (_e *MockIServiceRepo_Expecter) GetPackageItemsByPackageID(ctx interface{}, servicePackageID interface{}) *MockIServiceRepo_GetPackageItemsByPackageID_Call {
	return &MockIServiceRepo_GetPackageItemsByPackageID_Call{Call: _e.mock.On("GetPackageItemsByPackageID", ctx, servicePackageID)}
}

func (_c *MockIServiceRepo_GetPackageItemsByPackageID_Call) Run(run func(ctx context.Context, servicePackageID int64)) *MockIServiceRepo_GetPackageItemsByPackageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_GetPackageItemsByPackageID_Call) Return(packageItemParams []param.PackageItemParam, err error) *MockIServiceRepo_GetPackageItemsByPackageID_Call {
	_c.Call.Return(packageItemParams, err)
	return _c
}

func (_c *MockIServiceRepo_GetPackageItemsByPackageID_Call) RunAndReturn(run func(ctx context.Context, servicePackageID int64) ([]param.PackageItemParam, error)) *MockIServiceRepo_GetPackageItemsByPackageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicePackagesByServiceID provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) GetServicePackagesByServiceID(ctx context.Context, serviceID int64) ([]param.ServicePackageParam, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetServicePackagesByServiceID")
	}

	var r0 []param.ServicePackageParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.ServicePackageParam, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.ServicePackageParam); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServicePackageParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_GetServicePackagesByServiceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicePackagesByServiceID'
type MockIServiceRepo_GetServicePackagesByServiceID_Call struct {
	*mock.Call
}

// GetServicePackagesByServiceID is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID int64
func (_e *MockIServiceRepo_Expecter) GetServicePackagesByServiceID(ctx interface{}, serviceID interface{}) *MockIServiceRepo_GetServicePackagesByServiceID_Call {
	return &MockIServiceRepo_GetServicePackagesByServiceID_Call{Call: _e.mock.On("GetServicePackagesByServiceID", ctx, serviceID)}
}

func (_c *MockIServiceRepo_GetServicePackagesByServiceID_Call) Run(run func(ctx context.Context, serviceID int64)) *MockIServiceRepo_GetServicePackagesByServiceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_GetServicePackagesByServiceID_Call) Return(servicePackageParams []param.ServicePackageParam, err error) *MockIServiceRepo_GetServicePackagesByServiceID_Call {
	_c.Call.Return(servicePackageParams, err)
	return _c
}

func (_c *MockIServiceRepo_GetServicePackagesByServiceID_Call) RunAndReturn(run func(ctx context.Context, serviceID int64) ([]param.ServicePackageParam, error)) *MockIServiceRepo_GetServicePackagesByServiceID_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicesByBusinessID provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) GetServicesByBusinessID(ctx context.Context, businessID int64) ([]param.ServiceParam, error) {
	ret := _mock.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetServicesByBusinessID")
	}

	var r0 []param.ServiceParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]param.ServiceParam, error)); ok {
		return returnFunc(ctx, businessID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []param.ServiceParam); ok {
		r0 = returnFunc(ctx, businessID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]param.ServiceParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_GetServicesByBusinessID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicesByBusinessID'
type MockIServiceRepo_GetServicesByBusinessID_Call struct {
	*mock.Call
}

// GetServicesByBusinessID is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID int64
func (_e *MockIServiceRepo_Expecter) GetServicesByBusinessID(ctx interface{}, businessID interface{}) *MockIServiceRepo_GetServicesByBusinessID_Call {
	return &MockIServiceRepo_GetServicesByBusinessID_Call{Call: _e.mock.On("GetServicesByBusinessID", ctx, businessID)}
}

func (_c *MockIServiceRepo_GetServicesByBusinessID_Call) Run(run func(ctx context.Context, businessID int64)) *MockIServiceRepo_GetServicesByBusinessID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_GetServicesByBusinessID_Call) Return(serviceParams []param.ServiceParam, err error) *MockIServiceRepo_GetServicesByBusinessID_Call {
	_c.Call.Return(serviceParams, err)
	return _c
}

func (_c *MockIServiceRepo_GetServicesByBusinessID_Call) RunAndReturn(run func(ctx context.Context, businessID int64) ([]param.ServiceParam, error)) *MockIServiceRepo_GetServicesByBusinessID_Call {
	_c.Call.Return(run)
	return _c
}

// HasBookingForService provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) HasBookingForService(ctx context.Context, serviceID int64) (bool, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for HasBookingForService")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_HasBookingForService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBookingForService'
type MockIServiceRepo_HasBookingForService_Call struct {
	*mock.Call
}

// HasBookingForService is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID int64
func (_e *MockIServiceRepo_Expecter) HasBookingForService(ctx interface{}, serviceID interface{}) *MockIServiceRepo_HasBookingForService_Call {
	return &MockIServiceRepo_HasBookingForService_Call{Call: _e.mock.On("HasBookingForService", ctx, serviceID)}
}

func (_c *MockIServiceRepo_HasBookingForService_Call) Run(run func(ctx context.Context, serviceID int64)) *MockIServiceRepo_HasBookingForService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_HasBookingForService_Call) Return(b bool, err error) *MockIServiceRepo_HasBookingForService_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIServiceRepo_HasBookingForService_Call) RunAndReturn(run func(ctx context.Context, serviceID int64) (bool, error)) *MockIServiceRepo_HasBookingForService_Call {
	_c.Call.Return(run)
	return _c
}

// InsertPackageItem provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) InsertPackageItem(ctx context.Context, tx *sql.Tx, p param.PackageItemParam) error {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertPackageItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.PackageItemParam) error); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceRepo_InsertPackageItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertPackageItem'
type MockIServiceRepo_InsertPackageItem_Call struct {
	*mock.Call
}

// InsertPackageItem is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.PackageItemParam
func (_e *MockIServiceRepo_Expecter) InsertPackageItem(ctx interface{}, tx interface{}, p interface{}) *MockIServiceRepo_InsertPackageItem_Call {
	return &MockIServiceRepo_InsertPackageItem_Call{Call: _e.mock.On("InsertPackageItem", ctx, tx, p)}
}

func (_c *MockIServiceRepo_InsertPackageItem_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.PackageItemParam)) *MockIServiceRepo_InsertPackageItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.PackageItemParam
		if args[2] != nil {
			arg2 = args[2].(param.PackageItemParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_InsertPackageItem_Call) Return(err error) *MockIServiceRepo_InsertPackageItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceRepo_InsertPackageItem_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.PackageItemParam) error) *MockIServiceRepo_InsertPackageItem_Call {
	_c.Call.Return(run)
	return _c
}

// InsertService provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) InsertService(ctx context.Context, tx *sql.Tx, p param.ServiceParam) (*param.ServiceParam, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertService")
	}

	var r0 *param.ServiceParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceParam) (*param.ServiceParam, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceParam) *param.ServiceParam); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.ServiceParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.ServiceParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_InsertService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertService'
type MockIServiceRepo_InsertService_Call struct {
	*mock.Call
}

// InsertService is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServiceParam
func (_e *MockIServiceRepo_Expecter) InsertService(ctx interface{}, tx interface{}, p interface{}) *MockIServiceRepo_InsertService_Call {
	return &MockIServiceRepo_InsertService_Call{Call: _e.mock.On("InsertService", ctx, tx, p)}
}

func (_c *MockIServiceRepo_InsertService_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServiceParam)) *MockIServiceRepo_InsertService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServiceParam
		if args[2] != nil {
			arg2 = args[2].(param.ServiceParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_InsertService_Call) Return(serviceParam *param.ServiceParam, err error) *MockIServiceRepo_InsertService_Call {
	_c.Call.Return(serviceParam, err)
	return _c
}

func (_c *MockIServiceRepo_InsertService_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServiceParam) (*param.ServiceParam, error)) *MockIServiceRepo_InsertService_Call {
	_c.Call.Return(run)
	return _c
}

// InsertServicePackage provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) InsertServicePackage(ctx context.Context, tx *sql.Tx, p param.ServicePackageParam) (*param.ServicePackageParam, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertServicePackage")
	}

	var r0 *param.ServicePackageParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServicePackageParam) (*param.ServicePackageParam, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServicePackageParam) *param.ServicePackageParam); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.ServicePackageParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.ServicePackageParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_InsertServicePackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertServicePackage'
type MockIServiceRepo_InsertServicePackage_Call struct {
	*mock.Call
}

// InsertServicePackage is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServicePackageParam
func (_e *MockIServiceRepo_Expecter) InsertServicePackage(ctx interface{}, tx interface{}, p interface{}) *MockIServiceRepo_InsertServicePackage_Call {
	return &MockIServiceRepo_InsertServicePackage_Call{Call: _e.mock.On("InsertServicePackage", ctx, tx, p)}
}

func (_c *MockIServiceRepo_InsertServicePackage_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServicePackageParam)) *MockIServiceRepo_InsertServicePackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServicePackageParam
		if args[2] != nil {
			arg2 = args[2].(param.ServicePackageParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_InsertServicePackage_Call) Return(servicePackageParam *param.ServicePackageParam, err error) *MockIServiceRepo_InsertServicePackage_Call {
	_c.Call.Return(servicePackageParam, err)
	return _c
}

func (_c *MockIServiceRepo_InsertServicePackage_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServicePackageParam) (*param.ServicePackageParam, error)) *MockIServiceRepo_InsertServicePackage_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteService provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) SoftDeleteService(ctx context.Context, tx *sql.Tx, serviceID int64, businessID int64) error {
	ret := _mock.Called(ctx, tx, serviceID, businessID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int64, int64) error); ok {
		r0 = returnFunc(ctx, tx, serviceID, businessID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceRepo_SoftDeleteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteService'
type MockIServiceRepo_SoftDeleteService_Call struct {
	*mock.Call
}

// SoftDeleteService is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - serviceID int64
//   - businessID int64
func (_e *MockIServiceRepo_Expecter) SoftDeleteService(ctx interface{}, tx interface{}, serviceID interface{}, businessID interface{}) *MockIServiceRepo_SoftDeleteService_Call {
	return &MockIServiceRepo_SoftDeleteService_Call{Call: _e.mock.On("SoftDeleteService", ctx, tx, serviceID, businessID)}
}

func (_c *MockIServiceRepo_SoftDeleteService_Call) Run(run func(ctx context.Context, tx *sql.Tx, serviceID int64, businessID int64)) *MockIServiceRepo_SoftDeleteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_SoftDeleteService_Call) Return(err error) *MockIServiceRepo_SoftDeleteService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceRepo_SoftDeleteService_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, serviceID int64, businessID int64) error) *MockIServiceRepo_SoftDeleteService_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateService provides a mock function for the type MockIServiceRepo
func (_mock *MockIServiceRepo) UpdateService(ctx context.Context, tx *sql.Tx, p param.ServiceParam) (*param.ServiceParam, error) {
	ret := _mock.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateService")
	}

	var r0 *param.ServiceParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceParam) (*param.ServiceParam, error)); ok {
		return returnFunc(ctx, tx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, param.ServiceParam) *param.ServiceParam); ok {
		r0 = returnFunc(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*param.ServiceParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, param.ServiceParam) error); ok {
		r1 = returnFunc(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceRepo_UpdateService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateService'
type MockIServiceRepo_UpdateService_Call struct {
	*mock.Call
}

// UpdateService is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p param.ServiceParam
func (_e *MockIServiceRepo_Expecter) UpdateService(ctx interface{}, tx interface{}, p interface{}) *MockIServiceRepo_UpdateService_Call {
	return &MockIServiceRepo_UpdateService_Call{Call: _e.mock.On("UpdateService", ctx, tx, p)}
}

func (_c *MockIServiceRepo_UpdateService_Call) Run(run func(ctx context.Context, tx *sql.Tx, p param.ServiceParam)) *MockIServiceRepo_UpdateService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 param.ServiceParam
		if args[2] != nil {
			arg2 = args[2].(param.ServiceParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIServiceRepo_UpdateService_Call) Return(serviceParam *param.ServiceParam, err error) *MockIServiceRepo_UpdateService_Call {
	_c.Call.Return(serviceParam, err)
	return _c
}

func (_c *MockIServiceRepo_UpdateService_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, p param.ServiceParam) (*param.ServiceParam, error)) *MockIServiceRepo_UpdateService_Call {
	_c.Call.Return(run)
	return _c
}
