// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIProfileService creates a new instance of MockIProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIProfileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIProfileService {
	mock := &MockIProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIProfileService is an autogenerated mock type for the IProfileService type
type MockIProfileService struct {
	mock.Mock
}

type MockIProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIProfileService) EXPECT() *MockIProfileService_Expecter {
	return &MockIProfileService_Expecter{mock: &_m.Mock}
}
