package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"fyp/domain/param"
	"fyp/graph/model"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, user model.SignUpInput) (*model.AuthPayload, error) {
	result, err := r.App.AuthService.SignUp(ctx, param.SignUpParam{
		Username:      user.Username,
		Email:         user.Email,
		ContactNumber: user.ContactNumber,
		Password:      user.Password,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token: result.Token,
		User:  MapUser(result.User),
	}, nil
}

// LogIn is the resolver for the logIn field.
func (r *mutationResolver) LogIn(ctx context.Context, user model.LogInInput) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: LogIn - logIn"))
}

// Empty is the resolver for the _empty field.
func (r *queryResolver) Empty(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
