type Staff {
  staffId: ID!
  userId: ID!
  user: User!
  businessId: ID!
  business: BusinessProfile!
  businessName: String!
  name: String!
  email: String!
  mustResetPassword: Boolean!
  contactNumber: String!
  position: String
  workingHours: [StaffWorkingHour!]!
  leaveApplications: [LeaveApplication!]!
  serviceSlots: [ServiceSlot!]!
  recurringSchedules: [RecurringSchedule!]!
  hasBooking: Boolean!
  deletedAt: DateTime
}

type StaffWorkingHour {
  staffWorkHourId: ID!
  staffId: ID!
  staff: Staff!
  day: DayOfWeek!
  startTime: Time!
  endTime: Time!
  deletedAt: DateTime
}

input StaffInput {
  name: String!
  email: String!
  contactNumber: String!
  position: String!
  password: String!
  workingHours: [WorkingHourInput!]!
}

input UpdateStaffInput {
  name: String!
  email: String!
  contactNumber: String!
  position: String!
}

extend type Query {
  displayStaff: [Staff!]!
}

extend type Mutation {
  registerStaff(staff: StaffInput): Boolean!
  updateStaff(staffId: ID!, staff: UpdateStaffInput!): Staff!
  deleteStaff(staffId: ID!): Boolean!
}
