type Service {
  serviceId: ID!
  businessId: ID!
  business: BusinessProfile!
  serviceName: String!
  description: String
  serviceOptions: [ServiceOption!]!
  deletedAt: DateTime
}

type ServiceOption {
  serviceOptionId: ID!
  serviceId: ID!
  service: Service!
  serviceOptionName: String!
  description: String
  serviceOptionItems: [ServiceOptionItem!]!
  serviceSlotOptions: [ServiceSlotOption!]!
  recurringSchedules: [RecurringSchedule!]!
  deletedAt: DateTime
}

type ServiceOptionItem {
  serviceOptionItemId: ID!
  serviceOptionId: ID!
  servicePackage: ServiceOption!
  serviceOptionItemName: String!
  deletedAt: DateTime
}

input ServiceOptionItemInput {
  serviceOptionItemName: String!
}

input ServiceOptionInput {
  serviceOptionName: String!
  description: String
  serviceOptionItems: [ServiceOptionItemInput!]!
}

input ServiceInput {
  serviceName: String!
  description: String
  serviceOptions: [ServiceOptionInput!]!
}

extend type Query {
  displayServices: [Service!]!
}

extend type Mutation {
  createService(service: ServiceInput!): Service!
  updateService(serviceId: ID!, service: ServiceInput!): Service!
  deleteService(serviceId: ID!): Boolean!
}