package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"fyp/domain/param"
	"fyp/graph/graphErrs"
	"fyp/graph/model"
	"fyp/internal/contexts"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, user model.SignUpInput) (*model.AuthPayload, error) {
	result, err := r.App.AuthService.SignUp(ctx, param.SignUpParam{
		Username:      user.Username,
		Email:         user.Email,
		ContactNumber: user.ContactNumber,
		Password:      user.Password,
	})
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	return &model.AuthPayload{
		Token: result.Token,
		User:  MapUser(result.User),
	}, nil
}

// LogIn is the resolver for the logIn field.
func (r *mutationResolver) LogIn(ctx context.Context, user model.LogInInput) (*model.AuthPayload, error) {
	result, err := r.App.AuthService.LogIn(ctx, param.LogInParam{
		Email:    user.Email,
		Password: user.Password,
	})
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	return &model.AuthPayload{
		Token: result.Token,
		User:  MapUser(result.User),
	}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, user model.UpdateProfileInput) (*model.User, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	err = r.App.ProfileService.UpdateProfile(ctx, param.ProfileParam{
		UserId:        int(currentUser.UserID),
		Username:      user.Username,
		Email:         user.Email,
		ContactNumber: user.ContactNumber,
	})
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	userInfo, err := r.App.AuthService.GetUserProfile(ctx, user.Email)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return MapUser(userInfo), nil
}

// Empty is the resolver for the _empty field.
func (r *queryResolver) Empty(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// UserProfile is the resolver for the userProfile field.
func (r *queryResolver) UserProfile(ctx context.Context) (*model.User, error) {
	user, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	userInfo, err := r.App.AuthService.GetUserProfile(ctx, user.Email)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	return MapUser(userInfo), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
