scalar Date
scalar Time
scalar DateTime

enum DayOfWeek {
  monday
  tuesday
  wednesday
  thursday
  friday
  saturday
  sunday
}

enum LeaveStatus {
  PENDING
  APPROVED
  REJECTED
}

enum BookingStatus {
  ACCEPTED
  RESCHEDULED
  CANCELLED
  PAST
  REJECTED
  PENDING
}

enum BookingType {
  ONLINE
  WALK_IN
}

type User {
  userId: ID!
  username: String!
  email: String!
  contactNumber: String!
  failedLoginAttempts: Int!
  lockedUntil: DateTime
  businessProfile: BusinessProfile
  staffProfile: Staff
  bookings: [Booking!]!
}

type AuthPayload {
  token: String!
  user: User!
}

type BusinessProfile {
  businessId: ID!
  ownerUserId: ID!
  owner: User!
  businessName: String!
  description: String
  address: String!
  imageUrl: String
  businessContactNumber: String!
  businessEmail: String!
  workingHours: [BusinessWorkingHour!]!
  services: [Service!]!
  staff: [Staff!]!
}

type BusinessWorkingHour {
  businessWorkHourId: ID!
  businessId: ID!
  business: BusinessProfile!
  day: DayOfWeek!
  startTime: Time!
  endTime: Time!
  deletedAt: DateTime
}

type Service {
  serviceId: ID!
  businessId: ID!
  business: BusinessProfile!
  serviceName: String!
  description: String
  servicePackages: [ServicePackage!]!
  deletedAt: DateTime
}

type ServicePackage {
  servicePackageId: ID!
  serviceId: ID!
  service: Service!
  servicePackageName: String!
  description: String
  packageItems: [PackageItem!]!
  serviceSlotPackages: [ServiceSlotPackage!]!
  recurringSchedules: [RecurringSchedule!]!
  deletedAt: DateTime
}

type PackageItem {
  packageItemId: ID!
  servicePackageId: ID!
  servicePackage: ServicePackage!
  packageItemName: String!
  deletedAt: DateTime
}

type Staff {
  staffId: ID!
  userId: ID!
  user: User!
  businessId: ID!
  business: BusinessProfile!
  name: String!
  contactNumber: String!
  position: String
  workingHours: [StaffWorkingHour!]!
  leaveApplications: [LeaveApplication!]!
  serviceSlots: [ServiceSlot!]!
  recurringSchedules: [RecurringSchedule!]!
  deletedAt: DateTime
}

type StaffWorkingHour {
  staffWorkHourId: ID!
  staffId: ID!
  staff: Staff!
  day: DayOfWeek!
  startTime: Time!
  endTime: Time!
  deletedAt: DateTime
}

type LeaveApplication {
  leaveId: ID!
  staffId: ID!
  staff: Staff!
  startDate: Date!
  endDate: Date!
  justification: String
  fileUrl: String
  status: LeaveStatus!
  remark: String
  decidedAt: DateTime
  deletedAt: DateTime
  createdAt: DateTime!
}

type ServiceSlot {
  serviceSlotId: ID!
  staffId: ID
  staff: Staff
  date: Date!
  startTime: Time!
  endTime: Time!
  serviceSlotPackages: [ServiceSlotPackage!]!
  deletedAt: DateTime
  createdAt: DateTime!
  createdBy: ID
  creator: User
}

type ServiceSlotPackage {
  slotPackageId: ID!
  servicePackageId: ID!
  servicePackage: ServicePackage!
  serviceSlotId: ID!
  serviceSlot: ServiceSlot!
  bookings: [Booking!]!
  deletedAt: DateTime
}

type RecurringSchedule {
  recurringScheduleId: ID!
  staffId: ID!
  staff: Staff!
  servicePackageId: ID!
  servicePackage: ServicePackage!
  day: DayOfWeek!
  startTime: Time!
  endTime: Time!
  deletedAt: DateTime
  createdAt: DateTime!
  createdBy: ID
  creator: User
}

type Booking {
  bookingId: ID!
  userId: ID!
  user: User!
  slotPackageId: ID!
  slotPackage: ServiceSlotPackage!
  status: BookingStatus
  bookingType: BookingType!
  deletedAt: DateTime
  createdAt: DateTime!
  decidedAt: DateTime
  decidedBy: ID
  decidedByUser: User
}

type Query {
  _empty: String
  userProfile: User
  businessServices: [Service!]!
}

input SignUpInput {
  username: String!
  email: String!
  contactNumber: String!
  password: String!
}

input LogInInput{
  email: String!
  password: String!
}

input UpdateProfileInput{
  username: String!
  email: String!
  contactNumber: String
}

input BusinessProfileInput {
  businessName: String!
  description: String
  address: String!
  imageUrl: String
  businessContactNumber: String!
  businessEmail: String!
  workingHours: [WorkingHourInput!]!
}

input WorkingHourInput {
  day: DayOfWeek!
  startTime: Time!
  endTime: Time!
}

input PackageItemInput {
  packageItemName: String!
}

input ServicePackageInput {
  servicePackageName: String!
  description: String
  packageItems: [PackageItemInput!]!
}

input ServiceInput {
  serviceName: String!
  description: String
  servicePackages: [ServicePackageInput!]!
}

input StaffInput{
  name: String!
  email: String!
  contactNumber: String!
  position: String!
  workingHours: [WorkingHourInput!]!
}

type Mutation {
  signUp(user: SignUpInput!): AuthPayload!
  logIn(user: LogInInput!): AuthPayload!
  updateProfile(user: UpdateProfileInput!): User!
  registerBusinessProfile(business: BusinessProfileInput!): BusinessProfile!
  updateBusinessProfile(business: BusinessProfileInput!): BusinessProfile!
  createService(service: ServiceInput!): Service!
  updateService(serviceId: ID!, service: ServiceInput!): Service!
  deleteService(serviceId: ID!): Boolean!
  registerStaff(staff: StaffInput): Boolean!
}
