// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Booking struct {
	BookingID     string              `json:"bookingId"`
	UserID        string              `json:"userId"`
	User          *User               `json:"user"`
	SlotPackageID string              `json:"slotPackageId"`
	SlotPackage   *ServiceSlotPackage `json:"slotPackage"`
	Status        *BookingStatus      `json:"status,omitempty"`
	BookingType   BookingType         `json:"bookingType"`
	DeletedAt     *string             `json:"deletedAt,omitempty"`
	CreatedAt     string              `json:"createdAt"`
	DecidedAt     *string             `json:"decidedAt,omitempty"`
	DecidedBy     *string             `json:"decidedBy,omitempty"`
	DecidedByUser *User               `json:"decidedByUser,omitempty"`
}

type BusinessProfile struct {
	BusinessID            string                 `json:"businessId"`
	OwnerUserID           string                 `json:"ownerUserId"`
	Owner                 *User                  `json:"owner"`
	BusinessName          string                 `json:"businessName"`
	Description           *string                `json:"description,omitempty"`
	Address               string                 `json:"address"`
	ImageURL              *string                `json:"imageUrl,omitempty"`
	BusinessContactNumber string                 `json:"businessContactNumber"`
	BusinessEmail         string                 `json:"businessEmail"`
	WorkingHours          []*BusinessWorkingHour `json:"workingHours"`
	Services              []*Service             `json:"services"`
	Staff                 []*Staff               `json:"staff"`
}

type BusinessProfileInput struct {
	BusinessName          string              `json:"businessName"`
	Description           *string             `json:"description,omitempty"`
	Address               string              `json:"address"`
	ImageURL              *string             `json:"imageUrl,omitempty"`
	BusinessContactNumber string              `json:"businessContactNumber"`
	BusinessEmail         string              `json:"businessEmail"`
	WorkingHours          []*WorkingHourInput `json:"workingHours"`
}

type BusinessWorkingHour struct {
	BusinessWorkHourID string           `json:"businessWorkHourId"`
	BusinessID         string           `json:"businessId"`
	Business           *BusinessProfile `json:"business"`
	Day                DayOfWeek        `json:"day"`
	StartTime          time.Time        `json:"startTime"`
	EndTime            time.Time        `json:"endTime"`
	DeletedAt          *string          `json:"deletedAt,omitempty"`
}

type LeaveApplication struct {
	LeaveID       string      `json:"leaveId"`
	StaffID       string      `json:"staffId"`
	Staff         *Staff      `json:"staff"`
	StartDate     string      `json:"startDate"`
	EndDate       string      `json:"endDate"`
	Justification *string     `json:"justification,omitempty"`
	FileURL       *string     `json:"fileUrl,omitempty"`
	Status        LeaveStatus `json:"status"`
	Remark        *string     `json:"remark,omitempty"`
	DecidedAt     *string     `json:"decidedAt,omitempty"`
	DeletedAt     *string     `json:"deletedAt,omitempty"`
	CreatedAt     string      `json:"createdAt"`
}

type LogInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PackageItem struct {
	PackageItemID    string          `json:"packageItemId"`
	ServicePackageID string          `json:"servicePackageId"`
	ServicePackage   *ServicePackage `json:"servicePackage"`
	PackageItemName  string          `json:"packageItemName"`
	DeletedAt        *string         `json:"deletedAt,omitempty"`
}

type PackageItemInput struct {
	PackageItemName string `json:"packageItemName"`
}

type Query struct {
}

type RecurringSchedule struct {
	RecurringScheduleID string          `json:"recurringScheduleId"`
	StaffID             string          `json:"staffId"`
	Staff               *Staff          `json:"staff"`
	ServicePackageID    string          `json:"servicePackageId"`
	ServicePackage      *ServicePackage `json:"servicePackage"`
	Day                 DayOfWeek       `json:"day"`
	StartTime           time.Time       `json:"startTime"`
	EndTime             time.Time       `json:"endTime"`
	DeletedAt           *string         `json:"deletedAt,omitempty"`
	CreatedAt           string          `json:"createdAt"`
	CreatedBy           *string         `json:"createdBy,omitempty"`
	Creator             *User           `json:"creator,omitempty"`
}

type Service struct {
	ServiceID       string            `json:"serviceId"`
	BusinessID      string            `json:"businessId"`
	Business        *BusinessProfile  `json:"business"`
	ServiceName     string            `json:"serviceName"`
	Description     *string           `json:"description,omitempty"`
	ServicePackages []*ServicePackage `json:"servicePackages"`
	DeletedAt       *string           `json:"deletedAt,omitempty"`
}

type ServiceInput struct {
	ServiceName     string                 `json:"serviceName"`
	Description     *string                `json:"description,omitempty"`
	ServicePackages []*ServicePackageInput `json:"servicePackages"`
}

type ServicePackage struct {
	ServicePackageID    string                `json:"servicePackageId"`
	ServiceID           string                `json:"serviceId"`
	Service             *Service              `json:"service"`
	ServicePackageName  string                `json:"servicePackageName"`
	Description         *string               `json:"description,omitempty"`
	PackageItems        []*PackageItem        `json:"packageItems"`
	ServiceSlotPackages []*ServiceSlotPackage `json:"serviceSlotPackages"`
	RecurringSchedules  []*RecurringSchedule  `json:"recurringSchedules"`
	DeletedAt           *string               `json:"deletedAt,omitempty"`
}

type ServicePackageInput struct {
	ServicePackageName string              `json:"servicePackageName"`
	Description        *string             `json:"description,omitempty"`
	PackageItems       []*PackageItemInput `json:"packageItems"`
}

type ServiceSlot struct {
	ServiceSlotID       string                `json:"serviceSlotId"`
	StaffID             *string               `json:"staffId,omitempty"`
	Staff               *Staff                `json:"staff,omitempty"`
	Date                string                `json:"date"`
	StartTime           time.Time             `json:"startTime"`
	EndTime             time.Time             `json:"endTime"`
	ServiceSlotPackages []*ServiceSlotPackage `json:"serviceSlotPackages"`
	DeletedAt           *string               `json:"deletedAt,omitempty"`
	CreatedAt           string                `json:"createdAt"`
	CreatedBy           *string               `json:"createdBy,omitempty"`
	Creator             *User                 `json:"creator,omitempty"`
}

type ServiceSlotPackage struct {
	SlotPackageID    string          `json:"slotPackageId"`
	ServicePackageID string          `json:"servicePackageId"`
	ServicePackage   *ServicePackage `json:"servicePackage"`
	ServiceSlotID    string          `json:"serviceSlotId"`
	ServiceSlot      *ServiceSlot    `json:"serviceSlot"`
	Bookings         []*Booking      `json:"bookings"`
	DeletedAt        *string         `json:"deletedAt,omitempty"`
}

type SignUpInput struct {
	Username      string `json:"username"`
	Email         string `json:"email"`
	ContactNumber string `json:"contactNumber"`
	Password      string `json:"password"`
}

type Staff struct {
	StaffID            string               `json:"staffId"`
	UserID             string               `json:"userId"`
	User               *User                `json:"user"`
	BusinessID         string               `json:"businessId"`
	Business           *BusinessProfile     `json:"business"`
	Name               string               `json:"name"`
	ContactNumber      string               `json:"contactNumber"`
	Position           *string              `json:"position,omitempty"`
	WorkingHours       []*StaffWorkingHour  `json:"workingHours"`
	LeaveApplications  []*LeaveApplication  `json:"leaveApplications"`
	ServiceSlots       []*ServiceSlot       `json:"serviceSlots"`
	RecurringSchedules []*RecurringSchedule `json:"recurringSchedules"`
	DeletedAt          *string              `json:"deletedAt,omitempty"`
}

type StaffInput struct {
	Name          string              `json:"name"`
	Email         string              `json:"email"`
	ContactNumber string              `json:"contactNumber"`
	Position      string              `json:"position"`
	WorkingHours  []*WorkingHourInput `json:"workingHours"`
}

type StaffWorkingHour struct {
	StaffWorkHourID string    `json:"staffWorkHourId"`
	StaffID         string    `json:"staffId"`
	Staff           *Staff    `json:"staff"`
	Day             DayOfWeek `json:"day"`
	StartTime       time.Time `json:"startTime"`
	EndTime         time.Time `json:"endTime"`
	DeletedAt       *string   `json:"deletedAt,omitempty"`
}

type UpdateProfileInput struct {
	Username      string  `json:"username"`
	Email         string  `json:"email"`
	ContactNumber *string `json:"contactNumber,omitempty"`
}

type User struct {
	UserID              string           `json:"userId"`
	Username            string           `json:"username"`
	Email               string           `json:"email"`
	ContactNumber       string           `json:"contactNumber"`
	FailedLoginAttempts int32            `json:"failedLoginAttempts"`
	LockedUntil         *string          `json:"lockedUntil,omitempty"`
	BusinessProfile     *BusinessProfile `json:"businessProfile,omitempty"`
	StaffProfile        *Staff           `json:"staffProfile,omitempty"`
	Bookings            []*Booking       `json:"bookings"`
}

type WorkingHourInput struct {
	Day       DayOfWeek `json:"day"`
	StartTime time.Time `json:"startTime"`
	EndTime   time.Time `json:"endTime"`
}

type BookingStatus string

const (
	BookingStatusAccepted    BookingStatus = "ACCEPTED"
	BookingStatusRescheduled BookingStatus = "RESCHEDULED"
	BookingStatusCancelled   BookingStatus = "CANCELLED"
	BookingStatusPast        BookingStatus = "PAST"
	BookingStatusRejected    BookingStatus = "REJECTED"
	BookingStatusPending     BookingStatus = "PENDING"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusAccepted,
	BookingStatusRescheduled,
	BookingStatusCancelled,
	BookingStatusPast,
	BookingStatusRejected,
	BookingStatusPending,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusAccepted, BookingStatusRescheduled, BookingStatusCancelled, BookingStatusPast, BookingStatusRejected, BookingStatusPending:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BookingType string

const (
	BookingTypeOnline BookingType = "ONLINE"
	BookingTypeWalkIn BookingType = "WALK_IN"
)

var AllBookingType = []BookingType{
	BookingTypeOnline,
	BookingTypeWalkIn,
}

func (e BookingType) IsValid() bool {
	switch e {
	case BookingTypeOnline, BookingTypeWalkIn:
		return true
	}
	return false
}

func (e BookingType) String() string {
	return string(e)
}

func (e *BookingType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingType", str)
	}
	return nil
}

func (e BookingType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DayOfWeek string

const (
	DayOfWeekMonday    DayOfWeek = "monday"
	DayOfWeekTuesday   DayOfWeek = "tuesday"
	DayOfWeekWednesday DayOfWeek = "wednesday"
	DayOfWeekThursday  DayOfWeek = "thursday"
	DayOfWeekFriday    DayOfWeek = "friday"
	DayOfWeekSaturday  DayOfWeek = "saturday"
	DayOfWeekSunday    DayOfWeek = "sunday"
)

var AllDayOfWeek = []DayOfWeek{
	DayOfWeekMonday,
	DayOfWeekTuesday,
	DayOfWeekWednesday,
	DayOfWeekThursday,
	DayOfWeekFriday,
	DayOfWeekSaturday,
	DayOfWeekSunday,
}

func (e DayOfWeek) IsValid() bool {
	switch e {
	case DayOfWeekMonday, DayOfWeekTuesday, DayOfWeekWednesday, DayOfWeekThursday, DayOfWeekFriday, DayOfWeekSaturday, DayOfWeekSunday:
		return true
	}
	return false
}

func (e DayOfWeek) String() string {
	return string(e)
}

func (e *DayOfWeek) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DayOfWeek(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DayOfWeek", str)
	}
	return nil
}

func (e DayOfWeek) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DayOfWeek) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DayOfWeek) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LeaveStatus string

const (
	LeaveStatusPending  LeaveStatus = "PENDING"
	LeaveStatusApproved LeaveStatus = "APPROVED"
	LeaveStatusRejected LeaveStatus = "REJECTED"
)

var AllLeaveStatus = []LeaveStatus{
	LeaveStatusPending,
	LeaveStatusApproved,
	LeaveStatusRejected,
}

func (e LeaveStatus) IsValid() bool {
	switch e {
	case LeaveStatusPending, LeaveStatusApproved, LeaveStatusRejected:
		return true
	}
	return false
}

func (e LeaveStatus) String() string {
	return string(e)
}

func (e *LeaveStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LeaveStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LeaveStatus", str)
	}
	return nil
}

func (e LeaveStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LeaveStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LeaveStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
