// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Booking struct {
	BookingID     string             `json:"bookingId"`
	UserID        string             `json:"userId"`
	User          *User              `json:"user"`
	SlotOptionID  string             `json:"slotOptionId"`
	SlotOption    *ServiceSlotOption `json:"slotOption"`
	Status        *BookingStatus     `json:"status,omitempty"`
	BookingType   BookingType        `json:"bookingType"`
	DeletedAt     *string            `json:"deletedAt,omitempty"`
	CreatedAt     string             `json:"createdAt"`
	DecidedAt     *string            `json:"decidedAt,omitempty"`
	DecidedBy     *string            `json:"decidedBy,omitempty"`
	DecidedByUser *User              `json:"decidedByUser,omitempty"`
}

type BusinessProfile struct {
	BusinessID            string                 `json:"businessId"`
	OwnerUserID           string                 `json:"ownerUserId"`
	Owner                 *User                  `json:"owner"`
	BusinessName          string                 `json:"businessName"`
	Description           *string                `json:"description,omitempty"`
	Address               string                 `json:"address"`
	ImageURL              *string                `json:"imageUrl,omitempty"`
	BusinessContactNumber string                 `json:"businessContactNumber"`
	BusinessEmail         string                 `json:"businessEmail"`
	WorkingHours          []*BusinessWorkingHour `json:"workingHours"`
	Services              []*Service             `json:"services"`
	Staff                 []*Staff               `json:"staff"`
}

type BusinessProfileInput struct {
	BusinessName          string              `json:"businessName"`
	Description           *string             `json:"description,omitempty"`
	Address               string              `json:"address"`
	ImageURL              *string             `json:"imageUrl,omitempty"`
	BusinessContactNumber string              `json:"businessContactNumber"`
	BusinessEmail         string              `json:"businessEmail"`
	WorkingHours          []*WorkingHourInput `json:"workingHours"`
}

type BusinessWorkingHour struct {
	BusinessWorkHourID string           `json:"businessWorkHourId"`
	BusinessID         string           `json:"businessId"`
	Business           *BusinessProfile `json:"business"`
	Day                DayOfWeek        `json:"day"`
	StartTime          time.Time        `json:"startTime"`
	EndTime            time.Time        `json:"endTime"`
	DeletedAt          *string          `json:"deletedAt,omitempty"`
}

type LeaveApplication struct {
	LeaveID       string      `json:"leaveId"`
	StaffID       string      `json:"staffId"`
	Staff         *Staff      `json:"staff"`
	StartDate     string      `json:"startDate"`
	EndDate       string      `json:"endDate"`
	Justification *string     `json:"justification,omitempty"`
	FileURL       *string     `json:"fileUrl,omitempty"`
	Status        LeaveStatus `json:"status"`
	Remark        *string     `json:"remark,omitempty"`
	DecidedAt     *string     `json:"decidedAt,omitempty"`
	DeletedAt     *string     `json:"deletedAt,omitempty"`
	CreatedAt     string      `json:"createdAt"`
}

type LogInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RecurringSchedule struct {
	RecurringScheduleID string         `json:"recurringScheduleId"`
	StaffID             string         `json:"staffId"`
	Staff               *Staff         `json:"staff"`
	ServiceOptionID     string         `json:"serviceOptionId"`
	ServiceOption       *ServiceOption `json:"serviceOption"`
	Day                 DayOfWeek      `json:"day"`
	StartTime           time.Time      `json:"startTime"`
	EndTime             time.Time      `json:"endTime"`
	DeletedAt           *string        `json:"deletedAt,omitempty"`
	CreatedAt           string         `json:"createdAt"`
	CreatedBy           *string        `json:"createdBy,omitempty"`
	Creator             *User          `json:"creator,omitempty"`
}

type Service struct {
	ServiceID      string           `json:"serviceId"`
	BusinessID     string           `json:"businessId"`
	Business       *BusinessProfile `json:"business"`
	ServiceName    string           `json:"serviceName"`
	Description    *string          `json:"description,omitempty"`
	ServiceOptions []*ServiceOption `json:"serviceOptions"`
	DeletedAt      *string          `json:"deletedAt,omitempty"`
}

type ServiceInput struct {
	ServiceName    string                `json:"serviceName"`
	Description    *string               `json:"description,omitempty"`
	ServiceOptions []*ServiceOptionInput `json:"serviceOptions"`
}

type ServiceOption struct {
	ServiceOptionID    string               `json:"serviceOptionId"`
	ServiceID          string               `json:"serviceId"`
	Service            *Service             `json:"service"`
	ServiceOptionName  string               `json:"serviceOptionName"`
	Description        *string              `json:"description,omitempty"`
	ServiceOptionItems []*ServiceOptionItem `json:"serviceOptionItems"`
	ServiceSlotOptions []*ServiceSlotOption `json:"serviceSlotOptions"`
	RecurringSchedules []*RecurringSchedule `json:"recurringSchedules"`
	DeletedAt          *string              `json:"deletedAt,omitempty"`
}

type ServiceOptionInput struct {
	ServiceOptionName  string                    `json:"serviceOptionName"`
	Description        *string                   `json:"description,omitempty"`
	ServiceOptionItems []*ServiceOptionItemInput `json:"serviceOptionItems"`
}

type ServiceOptionItem struct {
	ServiceOptionItemID   string         `json:"serviceOptionItemId"`
	ServiceOptionID       string         `json:"serviceOptionId"`
	ServicePackage        *ServiceOption `json:"servicePackage"`
	ServiceOptionItemName string         `json:"serviceOptionItemName"`
	DeletedAt             *string        `json:"deletedAt,omitempty"`
}

type ServiceOptionItemInput struct {
	ServiceOptionItemName string `json:"serviceOptionItemName"`
}

type ServiceSlot struct {
	ServiceSlotID      string               `json:"serviceSlotId"`
	StaffID            *string              `json:"staffId,omitempty"`
	Staff              *Staff               `json:"staff,omitempty"`
	Date               string               `json:"date"`
	StartTime          time.Time            `json:"startTime"`
	EndTime            time.Time            `json:"endTime"`
	ServiceSlotOptions []*ServiceSlotOption `json:"serviceSlotOptions"`
	HasBooking         bool                 `json:"hasBooking"`
	DeletedAt          *string              `json:"deletedAt,omitempty"`
	CreatedAt          string               `json:"createdAt"`
	CreatedBy          *string              `json:"createdBy,omitempty"`
	Creator            *User                `json:"creator,omitempty"`
}

type ServiceSlotInput struct {
	StaffID          *string     `json:"staffId,omitempty"`
	Date             *string     `json:"date,omitempty"`
	DaysOfWeek       []DayOfWeek `json:"daysOfWeek,omitempty"`
	StartTime        time.Time   `json:"startTime"`
	EndTime          time.Time   `json:"endTime"`
	ServiceOptionIds []string    `json:"serviceOptionIds"`
}

type ServiceSlotOption struct {
	SlotOptionID    string         `json:"slotOptionId"`
	ServiceOptionID string         `json:"serviceOptionId"`
	ServiceOption   *ServiceOption `json:"serviceOption"`
	ServiceSlotID   string         `json:"serviceSlotId"`
	ServiceSlot     *ServiceSlot   `json:"serviceSlot"`
	Bookings        []*Booking     `json:"bookings"`
	DeletedAt       *string        `json:"deletedAt,omitempty"`
}

type SignUpInput struct {
	Username      string `json:"username"`
	Email         string `json:"email"`
	ContactNumber string `json:"contactNumber"`
	Password      string `json:"password"`
}

type Staff struct {
	StaffID            string               `json:"staffId"`
	UserID             string               `json:"userId"`
	User               *User                `json:"user"`
	BusinessID         string               `json:"businessId"`
	Business           *BusinessProfile     `json:"business"`
	Name               string               `json:"name"`
	Email              string               `json:"email"`
	MustResetPassword  bool                 `json:"mustResetPassword"`
	ContactNumber      string               `json:"contactNumber"`
	Position           *string              `json:"position,omitempty"`
	WorkingHours       []*StaffWorkingHour  `json:"workingHours"`
	LeaveApplications  []*LeaveApplication  `json:"leaveApplications"`
	ServiceSlots       []*ServiceSlot       `json:"serviceSlots"`
	RecurringSchedules []*RecurringSchedule `json:"recurringSchedules"`
	DeletedAt          *string              `json:"deletedAt,omitempty"`
}

type StaffInput struct {
	Name          string              `json:"name"`
	Email         string              `json:"email"`
	ContactNumber string              `json:"contactNumber"`
	Position      string              `json:"position"`
	WorkingHours  []*WorkingHourInput `json:"workingHours"`
}

type StaffWorkingHour struct {
	StaffWorkHourID string    `json:"staffWorkHourId"`
	StaffID         string    `json:"staffId"`
	Staff           *Staff    `json:"staff"`
	Day             DayOfWeek `json:"day"`
	StartTime       time.Time `json:"startTime"`
	EndTime         time.Time `json:"endTime"`
	DeletedAt       *string   `json:"deletedAt,omitempty"`
}

type UpdateProfileInput struct {
	Username      string  `json:"username"`
	Email         string  `json:"email"`
	ContactNumber *string `json:"contactNumber,omitempty"`
}

type UpdateStaffInput struct {
	Name          string `json:"name"`
	Email         string `json:"email"`
	ContactNumber string `json:"contactNumber"`
	Position      string `json:"position"`
}

type User struct {
	UserID              string           `json:"userId"`
	Username            string           `json:"username"`
	Email               string           `json:"email"`
	ContactNumber       string           `json:"contactNumber"`
	FailedLoginAttempts int32            `json:"failedLoginAttempts"`
	LockedUntil         *string          `json:"lockedUntil,omitempty"`
	MustResetPassword   bool             `json:"mustResetPassword"`
	BusinessProfile     *BusinessProfile `json:"businessProfile,omitempty"`
	StaffProfile        *Staff           `json:"staffProfile,omitempty"`
	Bookings            []*Booking       `json:"bookings"`
}

type WorkingHourInput struct {
	Day       DayOfWeek `json:"day"`
	StartTime time.Time `json:"startTime"`
	EndTime   time.Time `json:"endTime"`
}

type BookingStatus string

const (
	BookingStatusAccepted    BookingStatus = "ACCEPTED"
	BookingStatusRescheduled BookingStatus = "RESCHEDULED"
	BookingStatusCancelled   BookingStatus = "CANCELLED"
	BookingStatusPast        BookingStatus = "PAST"
	BookingStatusRejected    BookingStatus = "REJECTED"
	BookingStatusPending     BookingStatus = "PENDING"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusAccepted,
	BookingStatusRescheduled,
	BookingStatusCancelled,
	BookingStatusPast,
	BookingStatusRejected,
	BookingStatusPending,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusAccepted, BookingStatusRescheduled, BookingStatusCancelled, BookingStatusPast, BookingStatusRejected, BookingStatusPending:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BookingType string

const (
	BookingTypeOnline BookingType = "ONLINE"
	BookingTypeWalkIn BookingType = "WALK_IN"
)

var AllBookingType = []BookingType{
	BookingTypeOnline,
	BookingTypeWalkIn,
}

func (e BookingType) IsValid() bool {
	switch e {
	case BookingTypeOnline, BookingTypeWalkIn:
		return true
	}
	return false
}

func (e BookingType) String() string {
	return string(e)
}

func (e *BookingType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingType", str)
	}
	return nil
}

func (e BookingType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DayOfWeek string

const (
	DayOfWeekMonday    DayOfWeek = "monday"
	DayOfWeekTuesday   DayOfWeek = "tuesday"
	DayOfWeekWednesday DayOfWeek = "wednesday"
	DayOfWeekThursday  DayOfWeek = "thursday"
	DayOfWeekFriday    DayOfWeek = "friday"
	DayOfWeekSaturday  DayOfWeek = "saturday"
	DayOfWeekSunday    DayOfWeek = "sunday"
)

var AllDayOfWeek = []DayOfWeek{
	DayOfWeekMonday,
	DayOfWeekTuesday,
	DayOfWeekWednesday,
	DayOfWeekThursday,
	DayOfWeekFriday,
	DayOfWeekSaturday,
	DayOfWeekSunday,
}

func (e DayOfWeek) IsValid() bool {
	switch e {
	case DayOfWeekMonday, DayOfWeekTuesday, DayOfWeekWednesday, DayOfWeekThursday, DayOfWeekFriday, DayOfWeekSaturday, DayOfWeekSunday:
		return true
	}
	return false
}

func (e DayOfWeek) String() string {
	return string(e)
}

func (e *DayOfWeek) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DayOfWeek(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DayOfWeek", str)
	}
	return nil
}

func (e DayOfWeek) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DayOfWeek) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DayOfWeek) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LeaveStatus string

const (
	LeaveStatusPending  LeaveStatus = "PENDING"
	LeaveStatusApproved LeaveStatus = "APPROVED"
	LeaveStatusRejected LeaveStatus = "REJECTED"
)

var AllLeaveStatus = []LeaveStatus{
	LeaveStatusPending,
	LeaveStatusApproved,
	LeaveStatusRejected,
}

func (e LeaveStatus) IsValid() bool {
	switch e {
	case LeaveStatusPending, LeaveStatusApproved, LeaveStatusRejected:
		return true
	}
	return false
}

func (e LeaveStatus) String() string {
	return string(e)
}

func (e *LeaveStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LeaveStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LeaveStatus", str)
	}
	return nil
}

func (e LeaveStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LeaveStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LeaveStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
