// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ApplyLeaveInput struct {
	StartDate     string  `json:"startDate"`
	EndDate       string  `json:"endDate"`
	Justification *string `json:"justification,omitempty"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Booking struct {
	BookingID     string             `json:"bookingId"`
	UserID        string             `json:"userId"`
	User          *User              `json:"user"`
	SlotOptionID  string             `json:"slotOptionId"`
	SlotOption    *ServiceSlotOption `json:"slotOption"`
	Status        *BookingStatus     `json:"status,omitempty"`
	BookingType   BookingType        `json:"bookingType"`
	Description   *string            `json:"description,omitempty"`
	DeletedAt     *string            `json:"deletedAt,omitempty"`
	CreatedAt     string             `json:"createdAt"`
	DecidedAt     *string            `json:"decidedAt,omitempty"`
	DecidedBy     *string            `json:"decidedBy,omitempty"`
	DecidedByUser *User              `json:"decidedByUser,omitempty"`
}

type BookingDetail struct {
	BookingID       string        `json:"bookingId"`
	Status          BookingStatus `json:"status"`
	BookingType     BookingType   `json:"bookingType"`
	ServiceSlotID   string        `json:"serviceSlotId"`
	SlotOptionID    string        `json:"slotOptionId"`
	ServiceOptionID string        `json:"serviceOptionId"`
	Date            string        `json:"date"`
	StartTime       time.Time     `json:"startTime"`
	EndTime         time.Time     `json:"endTime"`
	ServiceName     string        `json:"serviceName"`
	OptionName      string        `json:"optionName"`
	StaffName       *string       `json:"staffName,omitempty"`
	CustomerName    string        `json:"customerName"`
	CustomerEmail   string        `json:"customerEmail"`
	BusinessID      string        `json:"businessId"`
	BusinessName    string        `json:"businessName"`
	Description     *string       `json:"description,omitempty"`
	CreatedAt       string        `json:"createdAt"`
}

type BookingSummary struct {
	TotalBookings      int32          `json:"totalBookings"`
	ByStatus           []*StatusCount `json:"byStatus"`
	ByType             []*TypeCount   `json:"byType"`
	TodayAcceptedCount int32          `json:"todayAcceptedCount"`
	PendingCount       int32          `json:"pendingCount"`
}

type BookingTrendPoint struct {
	Date  string `json:"date"`
	Count int32  `json:"count"`
}

type BusinessProfile struct {
	BusinessID            string                 `json:"businessId"`
	OwnerUserID           string                 `json:"ownerUserId"`
	Owner                 *User                  `json:"owner"`
	BusinessName          string                 `json:"businessName"`
	Description           *string                `json:"description,omitempty"`
	Address               string                 `json:"address"`
	ImageURL              *string                `json:"imageUrl,omitempty"`
	BusinessContactNumber string                 `json:"businessContactNumber"`
	BusinessEmail         string                 `json:"businessEmail"`
	WorkingHours          []*BusinessWorkingHour `json:"workingHours"`
	Services              []*Service             `json:"services"`
	Staff                 []*Staff               `json:"staff"`
}

type BusinessProfileInput struct {
	BusinessName          string              `json:"businessName"`
	Description           *string             `json:"description,omitempty"`
	Address               string              `json:"address"`
	ImageURL              *string             `json:"imageUrl,omitempty"`
	BusinessContactNumber string              `json:"businessContactNumber"`
	BusinessEmail         string              `json:"businessEmail"`
	WorkingHours          []*WorkingHourInput `json:"workingHours"`
}

type BusinessWorkingHour struct {
	BusinessWorkHourID string           `json:"businessWorkHourId"`
	BusinessID         string           `json:"businessId"`
	Business           *BusinessProfile `json:"business"`
	Day                DayOfWeek        `json:"day"`
	StartTime          time.Time        `json:"startTime"`
	EndTime            time.Time        `json:"endTime"`
	DeletedAt          *string          `json:"deletedAt,omitempty"`
}

type CancellationAnalysis struct {
	TotalCancelled           int32                  `json:"totalCancelled"`
	TotalRejected            int32                  `json:"totalRejected"`
	TotalCancelledOrRejected int32                  `json:"totalCancelledOrRejected"`
	CancelledOrRejectedRate  float64                `json:"cancelledOrRejectedRate"`
	ByService                []*ServiceCancellation `json:"byService"`
	ByStaff                  []*StaffCancellation   `json:"byStaff"`
}

type CustomerRetention struct {
	NewCustomers       int32 `json:"newCustomers"`
	ReturningCustomers int32 `json:"returningCustomers"`
	TotalCustomers     int32 `json:"totalCustomers"`
}

type LeaveApplication struct {
	LeaveID          string           `json:"leaveId"`
	StaffID          string           `json:"staffId"`
	Staff            *Staff           `json:"staff"`
	StaffName        string           `json:"staffName"`
	Position         *string          `json:"position,omitempty"`
	StartDate        string           `json:"startDate"`
	EndDate          string           `json:"endDate"`
	Justification    *string          `json:"justification,omitempty"`
	FileURL          *string          `json:"fileUrl,omitempty"`
	Status           LeaveStatus      `json:"status"`
	Remark           *string          `json:"remark,omitempty"`
	DecidedAt        *string          `json:"decidedAt,omitempty"`
	DeletedAt        *string          `json:"deletedAt,omitempty"`
	CreatedAt        string           `json:"createdAt"`
	AffectedBookings []*BookingDetail `json:"affectedBookings"`
}

type LogInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RecurringSchedule struct {
	RecurringScheduleID string         `json:"recurringScheduleId"`
	StaffID             string         `json:"staffId"`
	Staff               *Staff         `json:"staff"`
	ServiceOptionID     string         `json:"serviceOptionId"`
	ServiceOption       *ServiceOption `json:"serviceOption"`
	Day                 DayOfWeek      `json:"day"`
	StartTime           time.Time      `json:"startTime"`
	EndTime             time.Time      `json:"endTime"`
	DeletedAt           *string        `json:"deletedAt,omitempty"`
	CreatedAt           string         `json:"createdAt"`
	CreatedBy           *string        `json:"createdBy,omitempty"`
	Creator             *User          `json:"creator,omitempty"`
}

type Service struct {
	ServiceID      string           `json:"serviceId"`
	BusinessID     string           `json:"businessId"`
	Business       *BusinessProfile `json:"business"`
	ServiceName    string           `json:"serviceName"`
	Description    *string          `json:"description,omitempty"`
	ServiceOptions []*ServiceOption `json:"serviceOptions"`
	DeletedAt      *string          `json:"deletedAt,omitempty"`
}

type ServiceCancellation struct {
	ServiceID   string `json:"serviceId"`
	ServiceName string `json:"serviceName"`
	Count       int32  `json:"count"`
}

type ServiceFilterOption struct {
	ServiceIds  []string `json:"serviceIds"`
	ServiceName string   `json:"serviceName"`
	Deleted     bool     `json:"deleted"`
}

type ServiceInput struct {
	ServiceName    string                `json:"serviceName"`
	Description    *string               `json:"description,omitempty"`
	ServiceOptions []*ServiceOptionInput `json:"serviceOptions"`
}

type ServiceOption struct {
	ServiceOptionID    string               `json:"serviceOptionId"`
	ServiceID          string               `json:"serviceId"`
	Service            *Service             `json:"service"`
	ServiceOptionName  string               `json:"serviceOptionName"`
	Description        *string              `json:"description,omitempty"`
	ServiceOptionItems []*ServiceOptionItem `json:"serviceOptionItems"`
	ServiceSlotOptions []*ServiceSlotOption `json:"serviceSlotOptions"`
	RecurringSchedules []*RecurringSchedule `json:"recurringSchedules"`
	Removed            bool                 `json:"removed"`
	EffectiveFrom      *string              `json:"effectiveFrom,omitempty"`
	EffectiveUntil     *string              `json:"effectiveUntil,omitempty"`
	HasBooking         bool                 `json:"hasBooking"`
	DeletedAt          *string              `json:"deletedAt,omitempty"`
}

type ServiceOptionInput struct {
	ServiceOptionID     *string                   `json:"serviceOptionId,omitempty"`
	ServiceOptionName   string                    `json:"serviceOptionName"`
	Description         *string                   `json:"description,omitempty"`
	ServiceOptionItems  []*ServiceOptionItemInput `json:"serviceOptionItems"`
	EffectiveFrom       *string                   `json:"effectiveFrom,omitempty"`
	EffectiveUntil      *string                   `json:"effectiveUntil,omitempty"`
	ClearEffectiveUntil *bool                     `json:"clearEffectiveUntil,omitempty"`
}

type ServiceOptionItem struct {
	ServiceOptionItemID   string         `json:"serviceOptionItemId"`
	ServiceOptionID       string         `json:"serviceOptionId"`
	ServicePackage        *ServiceOption `json:"servicePackage"`
	ServiceOptionItemName string         `json:"serviceOptionItemName"`
	DeletedAt             *string        `json:"deletedAt,omitempty"`
}

type ServiceOptionItemInput struct {
	ServiceOptionItemName string `json:"serviceOptionItemName"`
}

type ServicePopularity struct {
	ServiceID    string `json:"serviceId"`
	ServiceName  string `json:"serviceName"`
	BookingCount int32  `json:"bookingCount"`
}

type ServiceSlot struct {
	ServiceSlotID      string               `json:"serviceSlotId"`
	StaffID            *string              `json:"staffId,omitempty"`
	Staff              *Staff               `json:"staff,omitempty"`
	Date               string               `json:"date"`
	StartTime          time.Time            `json:"startTime"`
	EndTime            time.Time            `json:"endTime"`
	ServiceSlotOptions []*ServiceSlotOption `json:"serviceSlotOptions"`
	HasBooking         bool                 `json:"hasBooking"`
	DeletedAt          *string              `json:"deletedAt,omitempty"`
	CreatedAt          string               `json:"createdAt"`
	CreatedBy          *string              `json:"createdBy,omitempty"`
	Creator            *User                `json:"creator,omitempty"`
}

type ServiceSlotInput struct {
	StaffID          *string     `json:"staffId,omitempty"`
	Date             *string     `json:"date,omitempty"`
	DaysOfWeek       []DayOfWeek `json:"daysOfWeek,omitempty"`
	StartTime        time.Time   `json:"startTime"`
	EndTime          time.Time   `json:"endTime"`
	ServiceOptionIds []string    `json:"serviceOptionIds"`
}

type ServiceSlotOption struct {
	SlotOptionID    string         `json:"slotOptionId"`
	ServiceOptionID string         `json:"serviceOptionId"`
	ServiceOption   *ServiceOption `json:"serviceOption"`
	ServiceSlotID   string         `json:"serviceSlotId"`
	ServiceSlot     *ServiceSlot   `json:"serviceSlot"`
	Bookings        []*Booking     `json:"bookings"`
	DeletedAt       *string        `json:"deletedAt,omitempty"`
}

type SignUpInput struct {
	Username      string `json:"username"`
	Email         string `json:"email"`
	ContactNumber string `json:"contactNumber"`
	Password      string `json:"password"`
}

type SlotReassignmentInput struct {
	ServiceSlotID string  `json:"serviceSlotId"`
	StaffID       *string `json:"staffId,omitempty"`
}

type SlotUtilization struct {
	TotalSlots      int32                 `json:"totalSlots"`
	BookedSlots     int32                 `json:"bookedSlots"`
	UtilizationRate float64               `json:"utilizationRate"`
	Sections        []*UtilizationSection `json:"sections"`
}

type Staff struct {
	StaffID            string               `json:"staffId"`
	UserID             string               `json:"userId"`
	User               *User                `json:"user"`
	BusinessID         string               `json:"businessId"`
	Business           *BusinessProfile     `json:"business"`
	Name               string               `json:"name"`
	Email              string               `json:"email"`
	MustResetPassword  bool                 `json:"mustResetPassword"`
	ContactNumber      string               `json:"contactNumber"`
	Position           *string              `json:"position,omitempty"`
	WorkingHours       []*StaffWorkingHour  `json:"workingHours"`
	LeaveApplications  []*LeaveApplication  `json:"leaveApplications"`
	ServiceSlots       []*ServiceSlot       `json:"serviceSlots"`
	RecurringSchedules []*RecurringSchedule `json:"recurringSchedules"`
	HasBooking         bool                 `json:"hasBooking"`
	DeletedAt          *string              `json:"deletedAt,omitempty"`
}

type StaffCancellation struct {
	StaffID       *string `json:"staffId,omitempty"`
	StaffName     string  `json:"staffName"`
	CustomerCount int32   `json:"customerCount"`
	StaffCount    int32   `json:"staffCount"`
}

type StaffInput struct {
	Name          string              `json:"name"`
	Email         string              `json:"email"`
	ContactNumber string              `json:"contactNumber"`
	Position      string              `json:"position"`
	Password      string              `json:"password"`
	WorkingHours  []*WorkingHourInput `json:"workingHours"`
}

type StaffUtilization struct {
	StaffID     *string `json:"staffId,omitempty"`
	StaffName   string  `json:"staffName"`
	Bookings    int32   `json:"bookings"`
	HoursBooked float64 `json:"hoursBooked"`
}

type StaffWorkingHour struct {
	StaffWorkHourID string    `json:"staffWorkHourId"`
	StaffID         string    `json:"staffId"`
	Staff           *Staff    `json:"staff"`
	Day             DayOfWeek `json:"day"`
	StartTime       time.Time `json:"startTime"`
	EndTime         time.Time `json:"endTime"`
	DeletedAt       *string   `json:"deletedAt,omitempty"`
}

type StatusCount struct {
	Status BookingStatus `json:"status"`
	Count  int32         `json:"count"`
}

type TypeCount struct {
	BookingType BookingType `json:"bookingType"`
	Count       int32       `json:"count"`
}

type UpdateProfileInput struct {
	Username      string  `json:"username"`
	Email         string  `json:"email"`
	ContactNumber *string `json:"contactNumber,omitempty"`
}

type UpdateStaffInput struct {
	Name          string `json:"name"`
	Email         string `json:"email"`
	ContactNumber string `json:"contactNumber"`
	Position      string `json:"position"`
}

type User struct {
	UserID              string           `json:"userId"`
	Username            string           `json:"username"`
	Email               string           `json:"email"`
	ContactNumber       string           `json:"contactNumber"`
	FailedLoginAttempts int32            `json:"failedLoginAttempts"`
	LockedUntil         *string          `json:"lockedUntil,omitempty"`
	MustResetPassword   bool             `json:"mustResetPassword"`
	BusinessProfile     *BusinessProfile `json:"businessProfile,omitempty"`
	StaffProfile        *Staff           `json:"staffProfile,omitempty"`
	Bookings            []*Booking       `json:"bookings"`
}

type UtilizationBreakdownPoint struct {
	Label       string `json:"label"`
	TotalSlots  int32  `json:"totalSlots"`
	BookedSlots int32  `json:"bookedSlots"`
}

type UtilizationSection struct {
	Subtitle string                       `json:"subtitle"`
	Points   []*UtilizationBreakdownPoint `json:"points"`
}

type WalkInInput struct {
	ServiceOptionID string    `json:"serviceOptionId"`
	StaffID         *string   `json:"staffId,omitempty"`
	Date            string    `json:"date"`
	StartTime       time.Time `json:"startTime"`
	EndTime         time.Time `json:"endTime"`
}

type WorkingHourInput struct {
	Day       DayOfWeek `json:"day"`
	StartTime time.Time `json:"startTime"`
	EndTime   time.Time `json:"endTime"`
}

type BookingStatus string

const (
	BookingStatusAccepted    BookingStatus = "ACCEPTED"
	BookingStatusRescheduled BookingStatus = "RESCHEDULED"
	BookingStatusCancelled   BookingStatus = "CANCELLED"
	BookingStatusPast        BookingStatus = "PAST"
	BookingStatusRejected    BookingStatus = "REJECTED"
	BookingStatusPending     BookingStatus = "PENDING"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusAccepted,
	BookingStatusRescheduled,
	BookingStatusCancelled,
	BookingStatusPast,
	BookingStatusRejected,
	BookingStatusPending,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusAccepted, BookingStatusRescheduled, BookingStatusCancelled, BookingStatusPast, BookingStatusRejected, BookingStatusPending:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BookingType string

const (
	BookingTypeOnline BookingType = "ONLINE"
	BookingTypeWalkIn BookingType = "WALK_IN"
)

var AllBookingType = []BookingType{
	BookingTypeOnline,
	BookingTypeWalkIn,
}

func (e BookingType) IsValid() bool {
	switch e {
	case BookingTypeOnline, BookingTypeWalkIn:
		return true
	}
	return false
}

func (e BookingType) String() string {
	return string(e)
}

func (e *BookingType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingType", str)
	}
	return nil
}

func (e BookingType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DayOfWeek string

const (
	DayOfWeekMonday    DayOfWeek = "monday"
	DayOfWeekTuesday   DayOfWeek = "tuesday"
	DayOfWeekWednesday DayOfWeek = "wednesday"
	DayOfWeekThursday  DayOfWeek = "thursday"
	DayOfWeekFriday    DayOfWeek = "friday"
	DayOfWeekSaturday  DayOfWeek = "saturday"
	DayOfWeekSunday    DayOfWeek = "sunday"
)

var AllDayOfWeek = []DayOfWeek{
	DayOfWeekMonday,
	DayOfWeekTuesday,
	DayOfWeekWednesday,
	DayOfWeekThursday,
	DayOfWeekFriday,
	DayOfWeekSaturday,
	DayOfWeekSunday,
}

func (e DayOfWeek) IsValid() bool {
	switch e {
	case DayOfWeekMonday, DayOfWeekTuesday, DayOfWeekWednesday, DayOfWeekThursday, DayOfWeekFriday, DayOfWeekSaturday, DayOfWeekSunday:
		return true
	}
	return false
}

func (e DayOfWeek) String() string {
	return string(e)
}

func (e *DayOfWeek) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DayOfWeek(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DayOfWeek", str)
	}
	return nil
}

func (e DayOfWeek) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DayOfWeek) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DayOfWeek) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LeaveStatus string

const (
	LeaveStatusPending  LeaveStatus = "PENDING"
	LeaveStatusApproved LeaveStatus = "APPROVED"
	LeaveStatusRejected LeaveStatus = "REJECTED"
)

var AllLeaveStatus = []LeaveStatus{
	LeaveStatusPending,
	LeaveStatusApproved,
	LeaveStatusRejected,
}

func (e LeaveStatus) IsValid() bool {
	switch e {
	case LeaveStatusPending, LeaveStatusApproved, LeaveStatusRejected:
		return true
	}
	return false
}

func (e LeaveStatus) String() string {
	return string(e)
}

func (e *LeaveStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LeaveStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LeaveStatus", str)
	}
	return nil
}

func (e LeaveStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LeaveStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LeaveStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SlotUtilizationGroupBy string

const (
	SlotUtilizationGroupByWeekday SlotUtilizationGroupBy = "weekday"
	SlotUtilizationGroupByDate    SlotUtilizationGroupBy = "date"
	SlotUtilizationGroupByMonth   SlotUtilizationGroupBy = "month"
	SlotUtilizationGroupByYear    SlotUtilizationGroupBy = "year"
)

var AllSlotUtilizationGroupBy = []SlotUtilizationGroupBy{
	SlotUtilizationGroupByWeekday,
	SlotUtilizationGroupByDate,
	SlotUtilizationGroupByMonth,
	SlotUtilizationGroupByYear,
}

func (e SlotUtilizationGroupBy) IsValid() bool {
	switch e {
	case SlotUtilizationGroupByWeekday, SlotUtilizationGroupByDate, SlotUtilizationGroupByMonth, SlotUtilizationGroupByYear:
		return true
	}
	return false
}

func (e SlotUtilizationGroupBy) String() string {
	return string(e)
}

func (e *SlotUtilizationGroupBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SlotUtilizationGroupBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SlotUtilizationGroupBy", str)
	}
	return nil
}

func (e SlotUtilizationGroupBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SlotUtilizationGroupBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SlotUtilizationGroupBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrendGranularity string

const (
	TrendGranularityDay   TrendGranularity = "day"
	TrendGranularityWeek  TrendGranularity = "week"
	TrendGranularityMonth TrendGranularity = "month"
)

var AllTrendGranularity = []TrendGranularity{
	TrendGranularityDay,
	TrendGranularityWeek,
	TrendGranularityMonth,
}

func (e TrendGranularity) IsValid() bool {
	switch e {
	case TrendGranularityDay, TrendGranularityWeek, TrendGranularityMonth:
		return true
	}
	return false
}

func (e TrendGranularity) String() string {
	return string(e)
}

func (e *TrendGranularity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrendGranularity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrendGranularity", str)
	}
	return nil
}

func (e TrendGranularity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrendGranularity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrendGranularity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
