package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fyp/domain/param"
	"fyp/graph"
	"fyp/graph/graphErrs"
	"fyp/graph/model"
	"fyp/internal/contexts"
)

// RegisterBusinessProfile is the resolver for the registerBusinessProfile field.
func (r *mutationResolver) RegisterBusinessProfile(ctx context.Context, business model.BusinessProfileInput) (*model.BusinessProfile, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	workingHours := make([]param.WorkingHourParam, len(business.WorkingHours))
	for i, wh := range business.WorkingHours {
		workingHours[i] = param.WorkingHourParam{
			Day:       string(wh.Day),
			StartTime: wh.StartTime,
			EndTime:   wh.EndTime,
		}
	}

	businessProfile, err := r.App.BusinessService.RegisterBusinessProfile(ctx, param.BusinessProfileParam{
		OwnerUserID:           currentUser.UserID,
		BusinessName:          business.BusinessName,
		Description:           business.Description,
		Address:               business.Address,
		ImageURL:              business.ImageURL,
		BusinessContactNumber: business.BusinessContactNumber,
		BusinessEmail:         business.BusinessEmail,
		WorkingHours:          workingHours,
	})
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	owner, err := r.App.AuthService.GetUserProfile(ctx, currentUser.Email)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	return graph.MapBusinessProfile(businessProfile, owner), nil
}

// UpdateBusinessProfile is the resolver for the updateBusinessProfile field.
func (r *mutationResolver) UpdateBusinessProfile(ctx context.Context, business model.BusinessProfileInput) (*model.BusinessProfile, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	_, err = r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	workingHours := make([]param.WorkingHourParam, len(business.WorkingHours))
	for i, wh := range business.WorkingHours {
		workingHours[i] = param.WorkingHourParam{
			Day:       string(wh.Day),
			StartTime: wh.StartTime,
			EndTime:   wh.EndTime,
		}
	}

	businessProfile, err := r.App.BusinessService.UpdateBusinessProfile(ctx, param.BusinessProfileParam{
		OwnerUserID:           currentUser.UserID,
		BusinessName:          business.BusinessName,
		Description:           business.Description,
		Address:               business.Address,
		ImageURL:              business.ImageURL,
		BusinessContactNumber: business.BusinessContactNumber,
		BusinessEmail:         business.BusinessEmail,
		WorkingHours:          workingHours,
	})
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	owner, err := r.App.AuthService.GetUserProfile(ctx, currentUser.Email)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	return graph.MapBusinessProfile(businessProfile, owner), nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
