package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"fyp/domain/param"
	"fyp/graph"
	"fyp/graph/graphErrs"
	"fyp/graph/model"
	"fyp/internal/contexts"
	"strconv"
)

// CreateService is the resolver for the createService field.
func (r *mutationResolver) CreateService(ctx context.Context, service model.ServiceInput) (*model.Service, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	businessProfile, err := r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	p := param.ServiceParam{
		BusinessID:  businessProfile.BusinessID,
		ServiceName: service.ServiceName,
		Description: service.Description,
	}
	for _, pkg := range service.ServiceOptions {
		pkgParam := param.ServiceOptionParam{
			ServiceOptionName: pkg.ServiceOptionName,
			Description:       pkg.Description,
		}
		for _, item := range pkg.ServiceOptionItems {
			pkgParam.ServiceOptionItems = append(pkgParam.ServiceOptionItems, param.ServiceOptionItemParam{
				ServiceOptionItemName: item.ServiceOptionItemName,
			})
		}
		p.ServiceOptions = append(p.ServiceOptions, pkgParam)
	}

	result, err := r.App.ServiceService.CreateService(ctx, p)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapService(result), nil
}

// UpdateService is the resolver for the updateService field.
func (r *mutationResolver) UpdateService(ctx context.Context, serviceID string, service model.ServiceInput) (*model.Service, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	businessProfile, err := r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	sid, err := strconv.ParseInt(serviceID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid service ID")
	}

	p := param.ServiceParam{
		ServiceID:   sid,
		BusinessID:  businessProfile.BusinessID,
		ServiceName: service.ServiceName,
		Description: service.Description,
	}
	for _, pkg := range service.ServiceOptions {
		pkgParam := param.ServiceOptionParam{
			ServiceOptionName: pkg.ServiceOptionName,
			Description:       pkg.Description,
		}
		for _, item := range pkg.ServiceOptionItems {
			pkgParam.ServiceOptionItems = append(pkgParam.ServiceOptionItems, param.ServiceOptionItemParam{
				ServiceOptionItemName: item.ServiceOptionItemName,
			})
		}
		p.ServiceOptions = append(p.ServiceOptions, pkgParam)
	}

	result, err := r.App.ServiceService.UpdateService(ctx, p)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapService(result), nil
}

// DeleteService is the resolver for the deleteService field.
func (r *mutationResolver) DeleteService(ctx context.Context, serviceID string) (bool, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return false, graphErrs.ToGraphQLError(err)
	}

	businessProfile, err := r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return false, graphErrs.ToGraphQLError(err)
	}

	sid, err := strconv.ParseInt(serviceID, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid service ID")
	}

	if err := r.App.ServiceService.DeleteService(ctx, sid, businessProfile.BusinessID); err != nil {
		return false, graphErrs.ToGraphQLError(err)
	}
	return true, nil
}

// DisplayServices is the resolver for the businessServices field.
func (r *queryResolver) DisplayServices(ctx context.Context) ([]*model.Service, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	// A staff member (no business profile of their own) can still list their
	// business's services — they need this to create/edit their own slots.
	businessID, _, err := resolveBusinessScope(ctx, r.Resolver, currentUser)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	services, err := r.App.ServiceService.GetServicesByBusinessID(ctx, businessID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	result := make([]*model.Service, len(services))
	for i := range services {
		result[i] = graph.MapService(&services[i])
	}
	return result, nil
}
