package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"fyp/domain/param"
	"fyp/graph"
	"fyp/graph/graphErrs"
	"fyp/graph/model"
	"fyp/internal/contexts"
)

// CreateServiceSlot is the resolver for the createServiceSlot field.
func (r *mutationResolver) CreateServiceSlot(ctx context.Context, input model.ServiceSlotInput) (*model.ServiceSlot, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	businessProfile, err := r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	var staffID *int64
	if input.StaffID != nil && *input.StaffID != "" {
		sid, err := parseID(*input.StaffID)
		if err != nil {
			return nil, fmt.Errorf("invalid staff ID")
		}
		staffID = &sid
	}

	packageIDs := make([]int64, 0, len(input.ServicePackageIds))
	for _, id := range input.ServicePackageIds {
		pid, err := parseID(id)
		if err != nil {
			return nil, fmt.Errorf("invalid package ID")
		}
		packageIDs = append(packageIDs, pid)
	}

	date := ""
	if input.Date != nil {
		date = *input.Date
	}
	daysOfWeek := make([]string, 0, len(input.DaysOfWeek))
	for _, d := range input.DaysOfWeek {
		daysOfWeek = append(daysOfWeek, string(d))
	}

	p := param.ServiceSlotParam{
		BusinessID:        businessProfile.BusinessID,
		StaffID:           staffID,
		Date:              date,
		DaysOfWeek:        daysOfWeek,
		StartTime:         input.StartTime,
		EndTime:           input.EndTime,
		ServicePackageIDs: packageIDs,
		CreatedBy:         currentUser.UserID,
	}

	result, err := r.App.ServiceSlotService.CreateServiceSlot(ctx, p)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapServiceSlot(result), nil
}

// ReassignServiceSlotStaff is the resolver for the reassignServiceSlotStaff field.
func (r *mutationResolver) ReassignServiceSlotStaff(ctx context.Context, serviceSlotID string, staffID *string) (*model.ServiceSlot, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	businessProfile, err := r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	slotID, err := parseID(serviceSlotID)
	if err != nil {
		return nil, fmt.Errorf("invalid service slot ID")
	}

	var newStaffID *int64
	if staffID != nil && *staffID != "" {
		sid, err := parseID(*staffID)
		if err != nil {
			return nil, fmt.Errorf("invalid staff ID")
		}
		newStaffID = &sid
	}

	result, err := r.App.ServiceSlotService.ReassignServiceSlotStaff(ctx, slotID, businessProfile.BusinessID, newStaffID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapServiceSlot(result), nil
}

// DeleteServiceSlot is the resolver for the deleteServiceSlot field.
func (r *mutationResolver) DeleteServiceSlot(ctx context.Context, serviceSlotID string, deleteFutureRecurring bool) (bool, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return false, graphErrs.ToGraphQLError(err)
	}

	businessProfile, err := r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return false, graphErrs.ToGraphQLError(err)
	}

	slotID, err := parseID(serviceSlotID)
	if err != nil {
		return false, fmt.Errorf("invalid service slot ID")
	}

	if err := r.App.ServiceSlotService.DeleteServiceSlot(ctx, slotID, businessProfile.BusinessID, deleteFutureRecurring); err != nil {
		return false, graphErrs.ToGraphQLError(err)
	}
	return true, nil
}

// DisplayServiceSlots is the resolver for the displayServiceSlots field.
func (r *queryResolver) DisplayServiceSlots(ctx context.Context, date string, staffID *string, serviceID *string, unassignedOnly *bool) ([]*model.ServiceSlot, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	businessProfile, err := r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	var staffFilter *int64
	if staffID != nil && *staffID != "" {
		id, err := parseID(*staffID)
		if err != nil {
			return nil, fmt.Errorf("invalid staff ID")
		}
		staffFilter = &id
	}
	var serviceFilter *int64
	if serviceID != nil && *serviceID != "" {
		id, err := parseID(*serviceID)
		if err != nil {
			return nil, fmt.Errorf("invalid service ID")
		}
		serviceFilter = &id
	}

	slots, err := r.App.ServiceSlotService.GetServiceSlots(ctx, businessProfile.BusinessID, date, staffFilter, serviceFilter, unassignedOnly != nil && *unassignedOnly)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	result := make([]*model.ServiceSlot, len(slots))
	for i := range slots {
		result[i] = graph.MapServiceSlot(&slots[i])
	}
	return result, nil
}

// AvailableStaffForSlot is the resolver for the availableStaffForSlot field.
func (r *queryResolver) AvailableStaffForSlot(ctx context.Context, serviceSlotID string) ([]*model.Staff, error) {
	currentUser, err := contexts.CurrentUser(ctx)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	businessProfile, err := r.App.BusinessService.GetBusinessProfileByOwnerID(ctx, currentUser.UserID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	slotID, err := parseID(serviceSlotID)
	if err != nil {
		return nil, fmt.Errorf("invalid service slot ID")
	}

	staffList, err := r.App.ServiceSlotService.GetAvailableStaffForSlot(ctx, slotID, businessProfile.BusinessID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}

	result := make([]*model.Staff, len(staffList))
	for i := range staffList {
		result[i] = graph.MapStaff(&staffList[i])
	}
	return result, nil
}
