package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fyp/graph"
	"fyp/graph/graphErrs"
	"fyp/graph/model"
)

// BookingSummary is the resolver for the bookingSummary field.
func (r *queryResolver) BookingSummary(ctx context.Context, from string, until string) (*model.BookingSummary, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.App.AnalyticsService.GetBookingSummary(ctx, businessID, from, until)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapBookingSummary(result), nil
}

// BookingTrend is the resolver for the bookingTrend field.
func (r *queryResolver) BookingTrend(ctx context.Context, from string, until string, granularity *model.TrendGranularity) ([]*model.BookingTrendPoint, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return nil, err
	}
	g := string(model.TrendGranularityDay)
	if granularity != nil {
		g = string(*granularity)
	}
	result, err := r.App.AnalyticsService.GetBookingTrend(ctx, businessID, from, until, g)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapBookingTrendPoints(result), nil
}

// ServicePopularity is the resolver for the servicePopularity field.
func (r *queryResolver) ServicePopularity(ctx context.Context, from string, until string) ([]*model.ServicePopularity, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.App.AnalyticsService.GetServicePopularity(ctx, businessID, from, until)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapServicePopularity(result), nil
}

// SlotUtilization is the resolver for the slotUtilization field.
func (r *queryResolver) SlotUtilization(ctx context.Context, from string, until string, groupBy *model.SlotUtilizationGroupBy) (*model.SlotUtilization, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return nil, err
	}
	g := string(model.SlotUtilizationGroupByWeekday)
	if groupBy != nil {
		g = string(*groupBy)
	}
	result, err := r.App.AnalyticsService.GetSlotUtilization(ctx, businessID, from, until, g)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapSlotUtilization(result), nil
}

// StaffUtilization is the resolver for the staffUtilization field.
func (r *queryResolver) StaffUtilization(ctx context.Context, from string, until string) ([]*model.StaffUtilization, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.App.AnalyticsService.GetStaffUtilization(ctx, businessID, from, until)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapStaffUtilization(result), nil
}

// CustomerRetention is the resolver for the customerRetention field.
func (r *queryResolver) CustomerRetention(ctx context.Context, from string, until string) (*model.CustomerRetention, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.App.AnalyticsService.GetCustomerRetention(ctx, businessID, from, until)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapCustomerRetention(result), nil
}

// CancellationServiceOptions is the resolver for the cancellationServiceOptions field.
func (r *queryResolver) CancellationServiceOptions(ctx context.Context) ([]*model.ServiceFilterOption, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.App.AnalyticsService.GetServiceFilterOptions(ctx, businessID)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapServiceFilterOptions(result), nil
}

// BusinessCreatedAt is the resolver for the businessCreatedAt field.
func (r *queryResolver) BusinessCreatedAt(ctx context.Context) (string, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return "", err
	}
	result, err := r.App.AnalyticsService.GetBusinessCreatedAt(ctx, businessID)
	if err != nil {
		return "", graphErrs.ToGraphQLError(err)
	}
	return result, nil
}

// CancellationAnalysis is the resolver for the cancellationAnalysis field.
func (r *queryResolver) CancellationAnalysis(ctx context.Context, from string, until string, staffIds []string, serviceIds []string) (*model.CancellationAnalysis, error) {
	businessID, err := r.ownerBusinessID(ctx)
	if err != nil {
		return nil, err
	}
	sids, err := parseIDs(staffIds)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	svcIDs, err := parseIDs(serviceIds)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	result, err := r.App.AnalyticsService.GetCancellationAnalysis(ctx, businessID, from, until, sids, svcIDs)
	if err != nil {
		return nil, graphErrs.ToGraphQLError(err)
	}
	return graph.MapCancellationAnalysis(result), nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
